-- 01_schemas_roles.sql: schemas, base-role usage, the RAW stage. Run as MED_ADMIN. Idempotent.
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE DATABASE {{DB}};

CREATE SCHEMA IF NOT EXISTS RAW COMMENT = 'Untouched Synthea CSV loads. Setup roles only.';
CREATE SCHEMA IF NOT EXISTS CLINICAL COMMENT = 'Normalised synthetic patient data, localised for India. Row access policy on every patient table.';
CREATE SCHEMA IF NOT EXISTS KNOWLEDGE COMMENT = 'Public medical documents only, never patient data (SEC-04).';
CREATE SCHEMA IF NOT EXISTS SECURITY COMMENT = 'Accounts, sessions, entitlements, policies and provisioning procedures.';
CREATE SCHEMA IF NOT EXISTS ANALYTICS COMMENT = 'Precomputed read models, answers, evidence, audit, pins, saved views.';

-- Usage so the per-user roles (through the base roles) can reach objects; table privileges are in 60_grants.sql.
GRANT USAGE ON DATABASE {{DB}} TO ROLE MED_DOCTOR;
GRANT USAGE ON DATABASE {{DB}} TO ROLE MED_ASSISTANT;
GRANT USAGE ON DATABASE {{DB}} TO ROLE MED_AGENT_READ;
GRANT USAGE ON DATABASE {{DB}} TO ROLE MED_API;
GRANT USAGE ON DATABASE {{DB}} TO ROLE MED_PROVISIONER;
GRANT USAGE ON SCHEMA CLINICAL TO ROLE MED_DOCTOR;
GRANT USAGE ON SCHEMA CLINICAL TO ROLE MED_ASSISTANT;
GRANT USAGE ON SCHEMA CLINICAL TO ROLE MED_AGENT_READ;
GRANT USAGE ON SCHEMA KNOWLEDGE TO ROLE MED_DOCTOR;
GRANT USAGE ON SCHEMA KNOWLEDGE TO ROLE MED_ASSISTANT;
GRANT USAGE ON SCHEMA KNOWLEDGE TO ROLE MED_AGENT_READ;
GRANT USAGE ON SCHEMA KNOWLEDGE TO ROLE MED_API;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE MED_DOCTOR;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE MED_ASSISTANT;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE MED_AGENT_READ;
GRANT USAGE ON SCHEMA SECURITY TO ROLE MED_API;
GRANT USAGE ON SCHEMA SECURITY TO ROLE MED_PROVISIONER;
GRANT USAGE ON SCHEMA CLINICAL TO ROLE MED_PROVISIONER;

-- RAW stage and file format for the Synthea CSVs
CREATE FILE FORMAT IF NOT EXISTS RAW.CSV_FORMAT
  TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 NULL_IF = ('') EMPTY_FIELD_AS_NULL = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;
CREATE STAGE IF NOT EXISTS RAW.SYNTHEA_STAGE FILE_FORMAT = RAW.CSV_FORMAT
  COMMENT = 'Localised Synthea CSV files, PUT by data/load_raw.py';
