-- 02_security_tables.sql: accounts, invites, sessions, entitlements, auth events. Run as MED_ADMIN.
-- CREATE ... IF NOT EXISTS: these hold live data and are never replaced by a rerun.
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE SCHEMA {{DB}}.SECURITY;

CREATE TABLE IF NOT EXISTS APP_USER (
  USER_ID VARCHAR NOT NULL COMMENT 'UUID. Builds the Snowflake role name U_<id without dashes>.',
  EMAIL VARCHAR NOT NULL COMMENT 'Lower-case, unique.',
  DISPLAY_NAME VARCHAR NOT NULL,
  ROLE_CODE VARCHAR NOT NULL COMMENT 'DOCTOR or ASSISTANT.',
  IS_ADMIN BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Doctors only: may manage users and entitlements.',
  SUPERVISING_DOCTOR_ID VARCHAR COMMENT 'Required for ASSISTANT.',
  STATUS VARCHAR NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE or DISABLED.',
  PASSWORD_HASH VARCHAR NOT NULL COMMENT 'argon2id encoded hash. Never logged or returned.',
  PASSWORD_UPDATED_AT TIMESTAMP_NTZ NOT NULL,
  FAILED_LOGINS NUMBER NOT NULL DEFAULT 0,
  LOCKED_UNTIL TIMESTAMP_NTZ,
  TOKEN_VERSION NUMBER NOT NULL DEFAULT 1 COMMENT 'Bumped on disable, password change, forced logout.',
  SNOWFLAKE_ROLE VARCHAR NOT NULL COMMENT 'U_<id>, created by PROVISION_USER.',
  CREATED_AT TIMESTAMP_NTZ NOT NULL,
  CREATED_BY VARCHAR,
  LAST_LOGIN_AT TIMESTAMP_NTZ,
  PRIMARY KEY (USER_ID),
  UNIQUE (EMAIL)
) COMMENT = 'One row per person who can sign in.';

CREATE TABLE IF NOT EXISTS USER_INVITE (
  INVITE_ID VARCHAR NOT NULL,
  EMAIL VARCHAR NOT NULL,
  DISPLAY_NAME VARCHAR NOT NULL,
  ROLE_CODE VARCHAR NOT NULL,
  IS_ADMIN BOOLEAN NOT NULL DEFAULT FALSE,
  SUPERVISING_DOCTOR_ID VARCHAR,
  PATIENT_IDS VARIANT COMMENT 'Patients to entitle on acceptance.',
  TOKEN_HASH VARCHAR NOT NULL COMMENT 'SHA-256 of the one-time token. The token is never stored.',
  STATUS VARCHAR NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, ACCEPTED, REVOKED, EXPIRED.',
  KIND VARCHAR NOT NULL DEFAULT 'INVITE' COMMENT 'INVITE or PASSWORD_RESET.',
  EXPIRES_AT TIMESTAMP_NTZ NOT NULL,
  INVITED_BY VARCHAR,
  CREATED_AT TIMESTAMP_NTZ NOT NULL,
  ACCEPTED_AT TIMESTAMP_NTZ,
  PRIMARY KEY (INVITE_ID)
) COMMENT = 'Admin-created invitations and password-reset links (72 hours).';

CREATE TABLE IF NOT EXISTS AUTH_SESSION (
  SESSION_ID VARCHAR NOT NULL,
  USER_ID VARCHAR NOT NULL,
  REFRESH_HASH VARCHAR NOT NULL COMMENT 'SHA-256 of the current refresh token.',
  PREVIOUS_HASH VARCHAR COMMENT 'Previous hash, kept to detect refresh-token reuse.',
  CREATED_AT TIMESTAMP_NTZ NOT NULL,
  LAST_USED_AT TIMESTAMP_NTZ NOT NULL,
  EXPIRES_AT TIMESTAMP_NTZ NOT NULL COMMENT 'Absolute lifetime: 7 days from creation.',
  REVOKED_AT TIMESTAMP_NTZ,
  USER_AGENT VARCHAR,
  IP_ADDRESS VARCHAR,
  PRIMARY KEY (SESSION_ID)
) COMMENT = 'One row per refresh-token lineage (one sign-in on one device).';

CREATE TABLE IF NOT EXISTS PATIENT_ENTITLEMENT (
  ENTITLEMENT_ID VARCHAR NOT NULL,
  PATIENT_ID VARCHAR NOT NULL,
  USER_ID VARCHAR NOT NULL,
  SNOWFLAKE_ROLE VARCHAR NOT NULL COMMENT 'Copied from APP_USER; read by the row access policy.',
  GRANTED_BY VARCHAR NOT NULL,
  GRANTED_AT TIMESTAMP_NTZ NOT NULL,
  REVOKED_AT TIMESTAMP_NTZ COMMENT 'Null means active.',
  PRIMARY KEY (ENTITLEMENT_ID)
) COMMENT = 'Who may see which patient. The row access policy reads this table.';

CREATE TABLE IF NOT EXISTS AUTH_EVENT (
  EVENT_ID VARCHAR NOT NULL,
  EVENT_AT TIMESTAMP_NTZ NOT NULL,
  EVENT_TYPE VARCHAR NOT NULL,
  USER_ID VARCHAR,
  ACTOR_ID VARCHAR,
  EMAIL_ATTEMPTED VARCHAR,
  IP_ADDRESS VARCHAR,
  USER_AGENT VARCHAR,
  DETAIL VARIANT COMMENT 'Structured extras, never secrets.',
  PRIMARY KEY (EVENT_ID)
) COMMENT = 'Append-only record of sign-ins, invitations and entitlement changes.';
