-- 03_clinical_tables.sql: normalised synthetic patient data. Run as MED_ADMIN. Structure only; 20_transform fills it.
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE SCHEMA {{DB}}.CLINICAL;

CREATE TABLE IF NOT EXISTS PATIENT (
  PATIENT_ID VARCHAR NOT NULL COMMENT 'Readable id such as P-1042.',
  SOURCE_ID VARCHAR COMMENT 'Synthea UUID.',
  FULL_NAME VARCHAR NOT NULL COMMENT 'Generated Indian name (synthetic).',
  BIRTH_DATE DATE NOT NULL,
  DEATH_DATE DATE,
  SEX VARCHAR NOT NULL COMMENT 'M or F.',
  MARITAL_STATUS VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  PIN_CODE VARCHAR,
  PHONE VARCHAR,
  PRIMARY KEY (PATIENT_ID)
) COMMENT = 'One row per synthetic patient. SSN, passport and similar source fields are never loaded.';

CREATE TABLE IF NOT EXISTS PROVIDER (
  PROVIDER_ID VARCHAR NOT NULL,
  NAME VARCHAR NOT NULL,
  SPECIALITY VARCHAR,
  ORGANIZATION_NAME VARCHAR,
  PRIMARY KEY (PROVIDER_ID)
) COMMENT = 'Clinicians and hospitals (synthetic, localised). Not patient-keyed.';

CREATE TABLE IF NOT EXISTS ENCOUNTER (
  ENCOUNTER_ID VARCHAR NOT NULL COMMENT 'Readable id such as ENC-20931.',
  SOURCE_ID VARCHAR,
  PATIENT_ID VARCHAR NOT NULL,
  STARTED_AT TIMESTAMP_NTZ NOT NULL COMMENT 'UTC.',
  ENDED_AT TIMESTAMP_NTZ,
  ENCOUNTER_CLASS VARCHAR COMMENT 'ambulatory, emergency, inpatient, outpatient, snf, urgentcare, virtual, wellness.',
  VISIT_KIND VARCHAR COMMENT 'OUTPATIENT, EMERGENCY or HOSPITALIZATION. Drives utilisation counts.',
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  PROVIDER_ID VARCHAR,
  REASON_CODE VARCHAR,
  REASON_DESCRIPTION VARCHAR,
  BASE_COST_INR NUMBER(12,2),
  TOTAL_CLAIM_COST_INR NUMBER(12,2),
  PAYER_COVERAGE_INR NUMBER(12,2),
  PRIMARY KEY (ENCOUNTER_ID)
) COMMENT = 'Visits: outpatient, emergency and hospital stays.';

CREATE TABLE IF NOT EXISTS DIAGNOSIS (
  DIAGNOSIS_ID VARCHAR NOT NULL COMMENT 'Readable id such as DX-3355.',
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR,
  CODE_SYSTEM VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR NOT NULL,
  ONSET_DATE DATE,
  RESOLVED_DATE DATE,
  IS_ACTIVE BOOLEAN NOT NULL COMMENT 'True while RESOLVED_DATE is null.',
  PRIMARY KEY (DIAGNOSIS_ID)
) COMMENT = 'Conditions and diagnoses.';

CREATE TABLE IF NOT EXISTS MEDICATION (
  MEDICATION_ID VARCHAR NOT NULL COMMENT 'Readable id such as RX-88231.',
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR,
  RXNORM_CODE VARCHAR,
  DESCRIPTION VARCHAR COMMENT 'Original medication string.',
  DRUG_ID VARCHAR COMMENT 'KNOWLEDGE.DRUG when the ingredient is in the corpus; null otherwise (the gap case).',
  DRUG_NAME VARCHAR COMMENT 'Normalised generic name for display.',
  STRENGTH_TEXT VARCHAR,
  DOSE_TEXT VARCHAR COMMENT 'Human sentence such as 1000 mg twice daily.',
  START_DATE DATE,
  STOP_DATE DATE,
  IS_ACTIVE BOOLEAN NOT NULL COMMENT 'True when there is no stop date.',
  LAST_CHANGE_DATE DATE,
  CHANGE_NOTE VARCHAR,
  DISPENSES NUMBER,
  TOTAL_COST_INR NUMBER(12,2),
  REASON_CODE VARCHAR,
  REASON_DESCRIPTION VARCHAR,
  PRIMARY KEY (MEDICATION_ID)
) COMMENT = 'Medications, active and stopped.';

CREATE TABLE IF NOT EXISTS LAB_RESULT (
  LAB_ID VARCHAR NOT NULL COMMENT 'Readable id such as LAB-77120.',
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR,
  OBSERVED_AT TIMESTAMP_NTZ NOT NULL COMMENT 'UTC.',
  LOINC_CODE VARCHAR,
  TEST_NAME VARCHAR NOT NULL,
  VALUE_NUM NUMBER(18,4),
  VALUE_TEXT VARCHAR,
  UNIT VARCHAR,
  REF_LOW NUMBER(18,4),
  REF_HIGH NUMBER(18,4),
  ABNORMAL_FLAG VARCHAR COMMENT 'LOW, HIGH, NORMAL or null when no range is known.',
  CATEGORY VARCHAR,
  PRIMARY KEY (LAB_ID)
) COMMENT = 'Laboratory results and selected vital signs.';

CREATE TABLE IF NOT EXISTS LAB_REFERENCE (
  LOINC_CODE VARCHAR NOT NULL,
  SHORT_NAME VARCHAR NOT NULL COMMENT 'Alias used by the API, e.g. eGFR.',
  TEST_NAME VARCHAR NOT NULL,
  UNIT VARCHAR,
  REF_LOW NUMBER(18,4),
  REF_HIGH NUMBER(18,4),
  SOURCE_NOTE VARCHAR,
  PRIMARY KEY (LOINC_CODE)
) COMMENT = 'Reference ranges for the demo tests. Synthea supplies none. Not patient-keyed.';

CREATE TABLE IF NOT EXISTS PROCEDURE (
  PROCEDURE_ID VARCHAR NOT NULL,
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR,
  CODE_SYSTEM VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  PERFORMED_AT TIMESTAMP_NTZ,
  BASE_COST_INR NUMBER(12,2),
  REASON_CODE VARCHAR,
  REASON_DESCRIPTION VARCHAR,
  PRIMARY KEY (PROCEDURE_ID)
) COMMENT = 'Procedures performed.';

CREATE TABLE IF NOT EXISTS CLAIM (
  CLAIM_ID VARCHAR NOT NULL COMMENT 'Readable id such as CLM-1024.',
  SOURCE_ID VARCHAR,
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR COMMENT 'The encounter this claim bills (Synthea APPOINTMENTID).',
  PROVIDER_ID VARCHAR,
  SERVICE_DATE DATE,
  SERVICE_TEXT VARCHAR COMMENT 'Short description of the billed service.',
  STATUS VARCHAR COMMENT 'SUBMITTED, APPROVED, PARTIAL or DENIED.',
  BILLED_INR NUMBER(12,2),
  APPROVED_INR NUMBER(12,2),
  OUTSTANDING_INR NUMBER(12,2),
  PRIMARY_DIAGNOSIS_CODE VARCHAR,
  PRIMARY KEY (CLAIM_ID)
) COMMENT = 'Claims linked to encounters. Amounts in INR.';

CREATE TABLE IF NOT EXISTS ALLERGY (
  ALLERGY_ID VARCHAR NOT NULL COMMENT 'Readable id such as ALG-1001.',
  PATIENT_ID VARCHAR NOT NULL,
  SUBSTANCE VARCHAR NOT NULL COMMENT 'What the patient reacts to, e.g. Penicillin or Aspirin.',
  REACTION VARCHAR COMMENT 'e.g. Rash, hives, anaphylaxis.',
  SEVERITY VARCHAR COMMENT 'MILD, MODERATE or SEVERE; null when not recorded.',
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  RECORDED_ON DATE,
  SOURCE VARCHAR COMMENT 'Where this came from: SEED, MANUAL or REPORT.',
  PRIMARY KEY (ALLERGY_ID)
) COMMENT = 'Documented allergies and intolerances. An empty set means none recorded, not none known.';

CREATE TABLE IF NOT EXISTS CLINICAL_NOTE (
  NOTE_ID VARCHAR NOT NULL COMMENT 'Readable id such as DOC-ED-20931.',
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR,
  NOTE_TYPE VARCHAR COMMENT 'ED_NOTE, DISCHARGE_SUMMARY or OUTPATIENT_NOTE.',
  TITLE VARCHAR NOT NULL,
  NOTE_DATE DATE NOT NULL,
  AUTHOR VARCHAR,
  BODY VARCHAR NOT NULL COMMENT 'Plain text. Treated as data, never as instructions.',
  CONTAINS_INJECTION BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Test marker only; never read by the agent.',
  PRIMARY KEY (NOTE_ID)
) COMMENT = 'Clinical notes and discharge summaries (generated).';

-- (Phase 2) Uploaded reports and what was read from them. Nothing read from a report reaches the clinical record until a
-- doctor approves it row by row (INTAKE procedures, snowflake/37_report_procedures.sql). Files live in a private stage.
CREATE TABLE IF NOT EXISTS REPORT (
  REPORT_ID VARCHAR NOT NULL COMMENT 'RPT-xxxxxxxx.',
  PATIENT_ID VARCHAR NOT NULL,
  FILENAME VARCHAR NOT NULL,
  MIME_TYPE VARCHAR NOT NULL COMMENT 'application/pdf, image/png or image/jpeg, checked from the file content.',
  SIZE_BYTES NUMBER NOT NULL,
  SHA256 VARCHAR NOT NULL COMMENT 'The same file is not stored twice for one patient.',
  STAGE_PATH VARCHAR NOT NULL COMMENT 'Path in INTAKE.REPORT_STAGE.',
  PAGE_COUNT NUMBER,
  STATUS VARCHAR NOT NULL COMMENT 'UPLOADED, PARSING, EXTRACTED, REVIEWED, REJECTED or FAILED.',
  STATUS_DETAIL VARCHAR,
  ATTEMPTS NUMBER NOT NULL DEFAULT 0,
  UPLOADED_BY VARCHAR NOT NULL,
  UPLOADED_AT TIMESTAMP_NTZ NOT NULL,
  EXTRACTED_AT TIMESTAMP_NTZ,
  REVIEWED_BY VARCHAR,
  REVIEWED_AT TIMESTAMP_NTZ,
  NAME_ON_REPORT VARCHAR COMMENT 'Patient name as printed on the report, for the wrong-patient check.',
  IDENTITY_STATUS VARCHAR COMMENT 'MATCH, MISMATCH or UNKNOWN against the patient the report was uploaded to.',
  IDENTITY_CONFIRMED_BY VARCHAR COMMENT 'Set when a doctor confirmed a mismatch before approving.',
  MODEL VARCHAR,
  ROWS_KEPT NUMBER,
  ROWS_DROPPED NUMBER COMMENT 'Rows the model proposed whose quote or value was not in the page text.',
  PRIMARY KEY (REPORT_ID)
) COMMENT = 'Uploaded patient reports. Extraction is staged, never written to the record until approved.';

CREATE TABLE IF NOT EXISTS REPORT_PAGE (
  REPORT_ID VARCHAR NOT NULL,
  PATIENT_ID VARCHAR NOT NULL,
  PAGE_NO NUMBER NOT NULL,
  PAGE_TEXT VARCHAR NOT NULL COMMENT 'Text read from the page. Treated as data, never as instructions.',
  PRIMARY KEY (REPORT_ID, PAGE_NO)
) COMMENT = 'The text of each report page, kept so every extracted row can be traced and highlighted.';

CREATE TABLE IF NOT EXISTS REPORT_ROW (
  ROW_ID VARCHAR NOT NULL COMMENT 'RRW-xxxxxxxx.',
  REPORT_ID VARCHAR NOT NULL,
  PATIENT_ID VARCHAR NOT NULL,
  KIND VARCHAR NOT NULL COMMENT 'LAB, MEDICATION or DIAGNOSIS.',
  FIELDS VARIANT NOT NULL COMMENT 'The values as they would be written (same names as the record forms).',
  COLLECTED_AT TIMESTAMP_NTZ COMMENT 'For a lab: when it was collected (UTC). Null when the report gives no date.',
  TIME_KNOWN BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'False when the report gave a date but no time; the time is never guessed.',
  SOURCE_PAGE NUMBER NOT NULL,
  SOURCE_QUOTE VARCHAR NOT NULL COMMENT 'The exact words on the page this row came from.',
  CONFIDENCE NUMBER(4,3) NOT NULL COMMENT 'Set by code from what could be checked, not by the model.',
  FLAGS VARIANT NOT NULL COMMENT 'unmatched_test, unmatched_drug, no_date, name_mismatch, duplicate.',
  STATUS VARCHAR NOT NULL COMMENT 'PENDING, ACCEPTED, EDITED, REJECTED or APPROVED.',
  DECIDED_BY VARCHAR,
  DECIDED_AT TIMESTAMP_NTZ,
  RECORD_ID VARCHAR COMMENT 'The clinical record created on approval.',
  VERSION NUMBER NOT NULL DEFAULT 1,
  PRIMARY KEY (ROW_ID)
) COMMENT = 'Rows read from a report, waiting for a doctor to accept, edit or reject each one.';
