-- 03_clinical_tables.sql: normalised synthetic patient data. Run as MED_ADMIN. Structure only; 20_transform fills it.
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE SCHEMA {{DB}}.CLINICAL;

CREATE TABLE IF NOT EXISTS PATIENT (
  PATIENT_ID VARCHAR NOT NULL COMMENT 'Readable id such as P-1042.',
  SOURCE_ID VARCHAR COMMENT 'Synthea UUID.',
  FULL_NAME VARCHAR NOT NULL COMMENT 'Generated Indian name (synthetic).',
  BIRTH_DATE DATE NOT NULL,
  DEATH_DATE DATE,
  SEX VARCHAR NOT NULL COMMENT 'M or F.',
  MARITAL_STATUS VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  PIN_CODE VARCHAR,
  PHONE VARCHAR,
  PRIMARY KEY (PATIENT_ID)
) COMMENT = 'One row per synthetic patient. SSN, passport and similar source fields are never loaded.';

CREATE TABLE IF NOT EXISTS PROVIDER (
  PROVIDER_ID VARCHAR NOT NULL,
  NAME VARCHAR NOT NULL,
  SPECIALITY VARCHAR,
  ORGANIZATION_NAME VARCHAR,
  PRIMARY KEY (PROVIDER_ID)
) COMMENT = 'Clinicians and hospitals (synthetic, localised). Not patient-keyed.';

CREATE TABLE IF NOT EXISTS ENCOUNTER (
  ENCOUNTER_ID VARCHAR NOT NULL COMMENT 'Readable id such as ENC-20931.',
  SOURCE_ID VARCHAR,
  PATIENT_ID VARCHAR NOT NULL,
  STARTED_AT TIMESTAMP_NTZ NOT NULL COMMENT 'UTC.',
  ENDED_AT TIMESTAMP_NTZ,
  ENCOUNTER_CLASS VARCHAR COMMENT 'ambulatory, emergency, inpatient, outpatient, snf, urgentcare, virtual, wellness.',
  VISIT_KIND VARCHAR COMMENT 'OUTPATIENT, EMERGENCY or HOSPITALIZATION. Drives utilisation counts.',
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  PROVIDER_ID VARCHAR,
  REASON_CODE VARCHAR,
  REASON_DESCRIPTION VARCHAR,
  BASE_COST_INR NUMBER(12,2),
  TOTAL_CLAIM_COST_INR NUMBER(12,2),
  PAYER_COVERAGE_INR NUMBER(12,2),
  PRIMARY KEY (ENCOUNTER_ID)
) COMMENT = 'Visits: outpatient, emergency and hospital stays.';

CREATE TABLE IF NOT EXISTS DIAGNOSIS (
  DIAGNOSIS_ID VARCHAR NOT NULL COMMENT 'Readable id such as DX-3355.',
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR,
  CODE_SYSTEM VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR NOT NULL,
  ONSET_DATE DATE,
  RESOLVED_DATE DATE,
  IS_ACTIVE BOOLEAN NOT NULL COMMENT 'True while RESOLVED_DATE is null.',
  PRIMARY KEY (DIAGNOSIS_ID)
) COMMENT = 'Conditions and diagnoses.';

CREATE TABLE IF NOT EXISTS MEDICATION (
  MEDICATION_ID VARCHAR NOT NULL COMMENT 'Readable id such as RX-88231.',
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR,
  RXNORM_CODE VARCHAR,
  DESCRIPTION VARCHAR COMMENT 'Original medication string.',
  DRUG_ID VARCHAR COMMENT 'KNOWLEDGE.DRUG when the ingredient is in the corpus; null otherwise (the gap case).',
  DRUG_NAME VARCHAR COMMENT 'Normalised generic name for display.',
  STRENGTH_TEXT VARCHAR,
  DOSE_TEXT VARCHAR COMMENT 'Human sentence such as 1000 mg twice daily.',
  START_DATE DATE,
  STOP_DATE DATE,
  IS_ACTIVE BOOLEAN NOT NULL COMMENT 'True when there is no stop date.',
  LAST_CHANGE_DATE DATE,
  CHANGE_NOTE VARCHAR,
  DISPENSES NUMBER,
  TOTAL_COST_INR NUMBER(12,2),
  REASON_CODE VARCHAR,
  REASON_DESCRIPTION VARCHAR,
  PRIMARY KEY (MEDICATION_ID)
) COMMENT = 'Medications, active and stopped.';

CREATE TABLE IF NOT EXISTS LAB_RESULT (
  LAB_ID VARCHAR NOT NULL COMMENT 'Readable id such as LAB-77120.',
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR,
  OBSERVED_AT TIMESTAMP_NTZ NOT NULL COMMENT 'UTC.',
  LOINC_CODE VARCHAR,
  TEST_NAME VARCHAR NOT NULL,
  VALUE_NUM NUMBER(18,4),
  VALUE_TEXT VARCHAR,
  UNIT VARCHAR,
  REF_LOW NUMBER(18,4),
  REF_HIGH NUMBER(18,4),
  ABNORMAL_FLAG VARCHAR COMMENT 'LOW, HIGH, NORMAL or null when no range is known.',
  CATEGORY VARCHAR,
  PRIMARY KEY (LAB_ID)
) COMMENT = 'Laboratory results and selected vital signs.';

CREATE TABLE IF NOT EXISTS LAB_REFERENCE (
  LOINC_CODE VARCHAR NOT NULL,
  SHORT_NAME VARCHAR NOT NULL COMMENT 'Alias used by the API, e.g. eGFR.',
  TEST_NAME VARCHAR NOT NULL,
  UNIT VARCHAR,
  REF_LOW NUMBER(18,4),
  REF_HIGH NUMBER(18,4),
  SOURCE_NOTE VARCHAR,
  PRIMARY KEY (LOINC_CODE)
) COMMENT = 'Reference ranges for the demo tests. Synthea supplies none. Not patient-keyed.';

CREATE TABLE IF NOT EXISTS PROCEDURE (
  PROCEDURE_ID VARCHAR NOT NULL,
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR,
  CODE_SYSTEM VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  PERFORMED_AT TIMESTAMP_NTZ,
  BASE_COST_INR NUMBER(12,2),
  REASON_CODE VARCHAR,
  REASON_DESCRIPTION VARCHAR,
  PRIMARY KEY (PROCEDURE_ID)
) COMMENT = 'Procedures performed.';

CREATE TABLE IF NOT EXISTS CLAIM (
  CLAIM_ID VARCHAR NOT NULL COMMENT 'Readable id such as CLM-1024.',
  SOURCE_ID VARCHAR,
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR COMMENT 'The encounter this claim bills (Synthea APPOINTMENTID).',
  PROVIDER_ID VARCHAR,
  SERVICE_DATE DATE,
  SERVICE_TEXT VARCHAR COMMENT 'Short description of the billed service.',
  STATUS VARCHAR COMMENT 'SUBMITTED, APPROVED, PARTIAL or DENIED.',
  BILLED_INR NUMBER(12,2),
  APPROVED_INR NUMBER(12,2),
  OUTSTANDING_INR NUMBER(12,2),
  PRIMARY_DIAGNOSIS_CODE VARCHAR,
  PRIMARY KEY (CLAIM_ID)
) COMMENT = 'Claims linked to encounters. Amounts in INR.';

CREATE TABLE IF NOT EXISTS ALLERGY (
  ALLERGY_ID VARCHAR NOT NULL COMMENT 'Readable id such as ALG-1001.',
  PATIENT_ID VARCHAR NOT NULL,
  SUBSTANCE VARCHAR NOT NULL COMMENT 'What the patient reacts to, e.g. Penicillin or Aspirin.',
  REACTION VARCHAR COMMENT 'e.g. Rash, hives, anaphylaxis.',
  SEVERITY VARCHAR COMMENT 'MILD, MODERATE or SEVERE; null when not recorded.',
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  RECORDED_ON DATE,
  SOURCE VARCHAR COMMENT 'Where this came from: SEED, MANUAL or REPORT.',
  PRIMARY KEY (ALLERGY_ID)
) COMMENT = 'Documented allergies and intolerances. An empty set means none recorded, not none known.';

CREATE TABLE IF NOT EXISTS CLINICAL_NOTE (
  NOTE_ID VARCHAR NOT NULL COMMENT 'Readable id such as DOC-ED-20931.',
  PATIENT_ID VARCHAR NOT NULL,
  ENCOUNTER_ID VARCHAR,
  NOTE_TYPE VARCHAR COMMENT 'ED_NOTE, DISCHARGE_SUMMARY or OUTPATIENT_NOTE.',
  TITLE VARCHAR NOT NULL,
  NOTE_DATE DATE NOT NULL,
  AUTHOR VARCHAR,
  BODY VARCHAR NOT NULL COMMENT 'Plain text. Treated as data, never as instructions.',
  CONTAINS_INJECTION BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Test marker only; never read by the agent.',
  PRIMARY KEY (NOTE_ID)
) COMMENT = 'Clinical notes and discharge summaries (generated).';
