-- 04_knowledge_tables.sql: public documents only (SEC-04). Run as MED_ADMIN. Filled by knowledge/ingest.
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE SCHEMA {{DB}}.KNOWLEDGE;

CREATE TABLE IF NOT EXISTS DRUG (
  DRUG_ID VARCHAR NOT NULL COMMENT 'DRG-001 style.',
  GENERIC_NAME VARCHAR NOT NULL COMMENT 'Lower-case ingredient, e.g. metformin.',
  DISPLAY_NAME VARCHAR NOT NULL,
  RXNORM_INGREDIENT VARCHAR,
  IN_CORPUS BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'True when a label is indexed.',
  IN_NLEM BOOLEAN NOT NULL DEFAULT FALSE,
  NLEM_LEVEL VARCHAR COMMENT 'P, S or T (India essential list).',
  PRIMARY KEY (DRUG_ID),
  UNIQUE (GENERIC_NAME)
) COMMENT = 'In-scope generics. Not patient-keyed.';

CREATE TABLE IF NOT EXISTS DRUG_NAME_MAP (
  MAP_ID VARCHAR NOT NULL,
  DRUG_ID VARCHAR NOT NULL,
  NAME_TEXT VARCHAR NOT NULL COMMENT 'Alias, lower-case.',
  NAME_KIND VARCHAR NOT NULL COMMENT 'SYNTHEA_INGREDIENT, INDIAN_BRAND or ALTERNATE_GENERIC.',
  SOURCE VARCHAR NOT NULL COMMENT 'SYNTHEA, AZ_INDIA or MANUAL.',
  COMPOSITION_TEXT VARCHAR,
  PRIMARY KEY (MAP_ID)
) COMMENT = 'Links names in patient data and Indian brands to a generic.';

CREATE TABLE IF NOT EXISTS DOCUMENT (
  DOCUMENT_ID VARCHAR NOT NULL COMMENT 'DOC-MET-001 style.',
  DRUG_ID VARCHAR,
  SOURCE VARCHAR NOT NULL COMMENT 'openFDA, ICMR or NLEM.',
  DOC_TYPE VARCHAR NOT NULL COMMENT 'DRUG_LABEL, GUIDELINE or ESSENTIAL_LIST.',
  TITLE VARCHAR NOT NULL,
  VERSION_LABEL VARCHAR COMMENT 'e.g. Label version 6.',
  EFFECTIVE_DATE DATE,
  RETRIEVED_AT TIMESTAMP_NTZ,
  INGESTED_AT TIMESTAMP_NTZ,
  SOURCE_URL VARCHAR,
  LICENSE_NOTE VARCHAR,
  SOURCE_META VARIANT COMMENT 'set_id, brand and manufacturer names, rxcui list.',
  CONTENT_HASH VARCHAR,
  PRIMARY KEY (DOCUMENT_ID)
) COMMENT = 'One row per source document (one label version per drug).';

CREATE TABLE IF NOT EXISTS DOCUMENT_CHUNK (
  CHUNK_ID VARCHAR NOT NULL COMMENT 'CH-0001 style.',
  DOCUMENT_ID VARCHAR NOT NULL,
  SECTION_KEY VARCHAR COMMENT 'openFDA field name such as warnings_and_cautions.',
  SECTION_NAME VARCHAR NOT NULL COMMENT 'Heading shown to users.',
  CHUNK_INDEX NUMBER NOT NULL,
  TEXT VARCHAR NOT NULL,
  SEARCH_TEXT VARCHAR COMMENT 'Drug | section | text: what the search index embeds.',
  RETRIEVED_DATE DATE COMMENT 'When the source document was fetched (citation field).',
  PAGE_NO NUMBER COMMENT 'Only where the source has pages.',
  TOKEN_COUNT NUMBER,
  DRUG_ID VARCHAR,
  DRUG_NAME VARCHAR,
  EFFECTIVE_DATE DATE,
  VERSION_LABEL VARCHAR,
  SOURCE VARCHAR,
  TITLE VARCHAR,
  PRIMARY KEY (CHUNK_ID)
) COMMENT = 'The unit that is indexed and cited. Denormalised so a citation is self-contained.';

CREATE TABLE IF NOT EXISTS SNAPSHOT (
  SNAPSHOT_DATE DATE NOT NULL,
  DOCUMENT_COUNT NUMBER,
  CHUNK_COUNT NUMBER,
  DRUG_COUNT NUMBER,
  NOTES VARCHAR
) COMMENT = 'One row: the controlled snapshot the UI shows next to evidence.';
ALTER TABLE DOCUMENT_CHUNK ADD COLUMN IF NOT EXISTS SEARCH_TEXT VARCHAR COMMENT 'Drug | section | text: what the search index embeds.';
ALTER TABLE DOCUMENT_CHUNK ADD COLUMN IF NOT EXISTS RETRIEVED_DATE DATE COMMENT 'When the source document was fetched (citation field).';
