-- 05_analytics_tables.sql: read models, answers, evidence, audit, pins, views, golden runs. Run as MED_ADMIN.
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE SCHEMA {{DB}}.ANALYTICS;

-- Read models (filled by 30_build_analytics.sql) -------------------------------------------------
CREATE TABLE IF NOT EXISTS PATIENT_360 (
  PATIENT_ID VARCHAR NOT NULL,
  FULL_NAME VARCHAR, AGE_YEARS NUMBER, SEX VARCHAR, CITY VARCHAR,
  ACTIVE_DIAGNOSES VARIANT COMMENT 'Array of {diagnosis_id, description, onset_year, code}.',
  LAST_ENCOUNTER_ID VARCHAR, LAST_ENCOUNTER_DATE DATE, LAST_ENCOUNTER_KIND VARCHAR, LAST_ENCOUNTER_LABEL VARCHAR,
  PREVIOUS_ENCOUNTER_DATE DATE COMMENT 'The visit before the last: baseline for what changed.',
  ACTIVE_MEDICATION_COUNT NUMBER,
  NEW_LAB_COUNT NUMBER, HAS_NEW_LAB BOOLEAN, HAS_NEW_MEDICATION_CHANGE BOOLEAN,
  HAS_RECENT_EMERGENCY BOOLEAN, HAS_NEW_DOCUMENT BOOLEAN,
  LAST_CHANGE_DATE DATE COMMENT 'Most recent encounter, lab, medication change or note.',
  PRIMARY KEY (PATIENT_ID)
) COMMENT = 'One row per patient: the Patient 360 overview. Precomputed.';

CREATE TABLE IF NOT EXISTS CURRENT_MEDICATIONS (
  PATIENT_ID VARCHAR NOT NULL, MEDICATION_ID VARCHAR NOT NULL, DRUG_ID VARCHAR, DRUG_NAME VARCHAR,
  DESCRIPTION VARCHAR, DOSE_TEXT VARCHAR, START_DATE DATE, LAST_CHANGE_DATE DATE, CHANGE_NOTE VARCHAR,
  IN_CORPUS BOOLEAN COMMENT 'True when the drug has an indexed label.',
  PRIMARY KEY (MEDICATION_ID)
) COMMENT = 'Active medications per patient.';

CREATE TABLE IF NOT EXISTS PATIENT_LAB_LATEST (
  PATIENT_ID VARCHAR NOT NULL, LOINC_CODE VARCHAR NOT NULL, SHORT_NAME VARCHAR, TEST_NAME VARCHAR,
  LATEST_LAB_ID VARCHAR, LATEST_VALUE NUMBER(18,4), LATEST_AT TIMESTAMP_NTZ,
  PREVIOUS_LAB_ID VARCHAR, PREVIOUS_VALUE NUMBER(18,4), PREVIOUS_AT TIMESTAMP_NTZ,
  UNIT VARCHAR, REF_LOW NUMBER(18,4), REF_HIGH NUMBER(18,4), ABNORMAL_FLAG VARCHAR,
  IS_NEW_SINCE_LAST_VISIT BOOLEAN,
  PRIMARY KEY (PATIENT_ID, LOINC_CODE)
) COMMENT = 'Latest and previous result per patient and test.';

CREATE TABLE IF NOT EXISTS PATIENT_TIMELINE (
  EVENT_ID VARCHAR NOT NULL, PATIENT_ID VARCHAR NOT NULL, EVENT_DATE DATE NOT NULL,
  EVENT_TYPE VARCHAR NOT NULL COMMENT 'ENCOUNTER, DIAGNOSIS, MEDICATION_START, MEDICATION_CHANGE, LAB_PANEL, CLAIM, NOTE.',
  TITLE VARCHAR, SUMMARY VARCHAR, RECORD_ID VARCHAR, RECORD_TABLE VARCHAR, ENCOUNTER_ID VARCHAR,
  PRIMARY KEY (EVENT_ID)
) COMMENT = 'Merged, date-ordered events. Lab results are grouped into one panel per day and encounter.';

CREATE TABLE IF NOT EXISTS UTILIZATION (
  PATIENT_ID VARCHAR NOT NULL,
  OPD_VISITS NUMBER, EMERGENCY_VISITS NUMBER, HOSPITALIZATIONS NUMBER, PROCEDURES NUMBER,
  BILLED_INR NUMBER(12,2), APPROVED_INR NUMBER(12,2), OUTSTANDING_INR NUMBER(12,2),
  PRIMARY KEY (PATIENT_ID)
) COMMENT = 'Trailing 12 months from the as-of date.';

CREATE TABLE IF NOT EXISTS DASHBOARD_WORKLIST (
  PATIENT_ID VARCHAR NOT NULL, FULL_NAME VARCHAR, AGE_YEARS NUMBER, SEX VARCHAR,
  MAIN_DIAGNOSES VARIANT COMMENT 'Up to three diagnosis descriptions.',
  LAST_ENCOUNTER_DATE DATE, LAST_ENCOUNTER_KIND VARCHAR, LAST_ENCOUNTER_LABEL VARCHAR,
  HAS_NEW_LAB BOOLEAN, NEW_LAB_COUNT NUMBER, HAS_NEW_MEDICATION_CHANGE BOOLEAN,
  HAS_RECENT_EMERGENCY BOOLEAN, HAS_NEW_DOCUMENT BOOLEAN, LAST_CHANGE_DATE DATE, FLAG_COUNT NUMBER,
  PRIMARY KEY (PATIENT_ID)
) COMMENT = 'Worklist and dashboard source. The row access policy scopes it per user.';

-- Answers, evidence, audit, pins, views, golden (written at run time) ----------------------------
CREATE TABLE IF NOT EXISTS ANSWER (
  ANSWER_ID VARCHAR NOT NULL, PATIENT_ID VARCHAR, USER_ID VARCHAR NOT NULL,
  KIND VARCHAR NOT NULL COMMENT 'SAFETY, CHANGED, MEDS, UTIL, LABS, KNOWLEDGE.',
  QUESTION VARCHAR, ROUTE VARCHAR, MODEL VARCHAR, CONFIDENCE NUMBER(5,4), PROMPT_HASH VARCHAR,
  ANSWER_JSON VARIANT COMMENT 'The validated answer object.',
  DROPPED_STATEMENTS VARIANT COMMENT 'What the validator removed, and why.',
  CREATED_AT TIMESTAMP_NTZ NOT NULL,
  PRIMARY KEY (ANSWER_ID)
) COMMENT = 'One row per stored answer. Backs the Why? panel. Own rows only.';

CREATE TABLE IF NOT EXISTS ANSWER_EVIDENCE (
  ANSWER_ID VARCHAR NOT NULL, EVIDENCE_ID VARCHAR NOT NULL COMMENT 'Scoped to the answer: P1, Q1, S1.',
  USER_ID VARCHAR NOT NULL, PATIENT_ID VARCHAR,
  EVIDENCE_KIND VARCHAR NOT NULL COMMENT 'PATIENT_RECORD, SQL or SOURCE_CHUNK.',
  RECORD_TYPE VARCHAR, RECORD_ID VARCHAR, RECORD_TABLE VARCHAR, RECORD_DATE DATE, VALUE_TEXT VARCHAR,
  SQL_TEXT VARCHAR, SQL_ROLE VARCHAR, ROW_COUNT NUMBER, RAN_AT TIMESTAMP_NTZ,
  CHUNK_ID VARCHAR, DOCUMENT_ID VARCHAR, SOURCE_SNAPSHOT VARIANT COMMENT 'Citation fields and text as shown.',
  MATCHED BOOLEAN,
  PRIMARY KEY (ANSWER_ID, EVIDENCE_ID)
) COMMENT = 'Evidence behind each answer: records, SQL and source chunks.';

CREATE TABLE IF NOT EXISTS COPILOT_AUDIT (
  AUDIT_ID VARCHAR NOT NULL, OCCURRED_AT TIMESTAMP_NTZ NOT NULL,
  USER_ID VARCHAR NOT NULL, ROLE_CODE VARCHAR, VIA VARCHAR COMMENT 'USER or AGENT.',
  ACTION VARCHAR NOT NULL, ROUTE VARCHAR, MODEL VARCHAR, CONFIDENCE NUMBER(5,4), COST_NOTE VARCHAR,
  PATIENT_ID VARCHAR, QUESTION VARCHAR, ANSWER_ID VARCHAR,
  PATIENT_EVIDENCE_IDS VARIANT, DOCUMENT_IDS VARIANT, STEPS VARIANT, PROMPT_HASH VARCHAR,
  OUTCOME VARCHAR NOT NULL COMMENT 'OK, DENIED, REFUSED, ERROR or ACTION_NOT_ALLOWED.',
  OUTCOME_DETAIL VARCHAR,
  PRIMARY KEY (AUDIT_ID)
) COMMENT = 'Append-only. Every Copilot question, agent action and denied attempt. Own rows only.';

CREATE TABLE IF NOT EXISTS PIN (
  PIN_ID VARCHAR NOT NULL, USER_ID VARCHAR NOT NULL, PATIENT_ID VARCHAR NOT NULL,
  ANSWER_ID VARCHAR NOT NULL, EVIDENCE_ID VARCHAR NOT NULL, LABEL VARCHAR, NOTE VARCHAR,
  IDEMPOTENCY_KEY VARCHAR, CREATED_AT TIMESTAMP_NTZ NOT NULL,
  PRIMARY KEY (PIN_ID)
) COMMENT = 'Evidence pinned to a patient workspace. Own rows only.';

CREATE TABLE IF NOT EXISTS SAVED_VIEW (
  VIEW_ID VARCHAR NOT NULL, USER_ID VARCHAR NOT NULL, PATIENT_ID VARCHAR NOT NULL,
  KIND VARCHAR NOT NULL COMMENT 'SAVED_VIEW or VISIT_BRIEF.', TITLE VARCHAR, CONTENT VARIANT,
  APPROVED_AT TIMESTAMP_NTZ, CREATED_AT TIMESTAMP_NTZ NOT NULL,
  PRIMARY KEY (VIEW_ID)
) COMMENT = 'Written only after the user approves a preview (FR-22). Own rows only.';

CREATE TABLE IF NOT EXISTS GOLDEN_RUN (
  RUN_ID VARCHAR NOT NULL, STARTED_AT TIMESTAMP_NTZ, FINISHED_AT TIMESTAMP_NTZ, STATUS VARCHAR,
  STARTED_BY VARCHAR, GOLDEN_TOTAL NUMBER, GOLDEN_PASSED NUMBER, ROUTING_TOTAL NUMBER, ROUTING_CORRECT NUMBER,
  PRIMARY KEY (RUN_ID)
) COMMENT = 'One row per golden-question run.';

CREATE TABLE IF NOT EXISTS GOLDEN_RESULT (
  RUN_ID VARCHAR NOT NULL, SEQ NUMBER NOT NULL, SET_NAME VARCHAR, QUESTION VARCHAR,
  EXPECTED VARCHAR, ACTUAL VARCHAR, ROUTE_EXPECTED VARCHAR, ROUTE_ACTUAL VARCHAR, RESULT VARCHAR,
  PRIMARY KEY (RUN_ID, SEQ)
) COMMENT = 'Per-question golden and routing results, failures included.';

-- A clinician's decision on a statement from a safety review (E3). Shared by everyone entitled to the patient, so it
-- carries PATIENT_RAP (not the own-rows policy). Status changes are audited by the API.
CREATE TABLE IF NOT EXISTS FINDING (
  FINDING_ID VARCHAR NOT NULL, PATIENT_ID VARCHAR NOT NULL,
  ANSWER_ID VARCHAR NOT NULL COMMENT 'The stored answer the statement came from.',
  CONSIDERATION_ID VARCHAR NOT NULL COMMENT 'The statement id inside that answer, e.g. C1.',
  SUMMARY VARCHAR NOT NULL COMMENT 'Copy of the statement text at the time it was raised.',
  STATUS VARCHAR NOT NULL COMMENT 'NEW, ACKNOWLEDGED, FLAGGED, DISMISSED or ESCALATED.',
  REASON VARCHAR COMMENT 'Required when dismissed.',
  FOLLOW_UP_ON DATE COMMENT 'Required when flagged.',
  ASSIGNED_TO VARCHAR COMMENT 'User id of the colleague an escalation went to.',
  CREATED_BY VARCHAR NOT NULL, CREATED_AT TIMESTAMP_NTZ NOT NULL,
  UPDATED_BY VARCHAR, UPDATED_AT TIMESTAMP_NTZ,
  PRIMARY KEY (FINDING_ID)
) COMMENT = 'Decisions on safety-review statements. Visible to everyone entitled to the patient.';

-- (Phase 3) A clinician's note that an abnormal result has been looked at. Shared by everyone entitled to the patient.
CREATE TABLE IF NOT EXISTS LAB_REVIEW (
  LAB_ID VARCHAR NOT NULL,
  PATIENT_ID VARCHAR NOT NULL,
  REVIEWED_BY VARCHAR NOT NULL,
  REVIEWED_AT TIMESTAMP_NTZ NOT NULL,
  PRIMARY KEY (LAB_ID)
) COMMENT = 'Marks an abnormal lab as reviewed so it leaves the pending list. Insert only. PATIENT_RAP.';


-- (Phase 5) One vector per patient for similar-patient search. Built from PATIENT_CASE_SUMMARY, which holds only age
-- band, sex, diagnoses, medicines and abnormal results: never a name, city, id or free-text note.
CREATE TABLE IF NOT EXISTS PATIENT_EMBEDDING (
  PATIENT_ID VARCHAR NOT NULL,
  SUMMARY_TEXT VARCHAR NOT NULL,
  SUMMARY_HASH VARCHAR NOT NULL COMMENT 'SHA-256 of the summary. An unchanged summary is never embedded again.',
  EMBEDDING VECTOR(FLOAT, 1024) NOT NULL,
  MODEL VARCHAR NOT NULL,
  BUILT_AT TIMESTAMP_NTZ NOT NULL,
  PRIMARY KEY (PATIENT_ID)
) COMMENT = 'Case embeddings for similar-patient search. PATIENT_RAP, so a user can only ever be shown matches among their own patients.';
