-- 06_policies.sql: row access policies and the procedure that (re)attaches them. Run as MED_ADMIN.
-- A table can carry only ONE row access policy, so three policies cover the three table kinds:
--   PATIENT_RAP       patient data: entitled patients only
--   PATIENT_OWN_RAP   answers, evidence, pins, saved views: own rows AND still entitled to the patient
--   OWN_RAP           audit: own rows only (a denied attempt names a patient the caller is not entitled to)
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE SCHEMA {{DB}}.SECURITY;

CREATE ROW ACCESS POLICY IF NOT EXISTS PATIENT_RAP AS (patient_id VARCHAR) RETURNS BOOLEAN -> TRUE;
ALTER ROW ACCESS POLICY PATIENT_RAP SET BODY ->
  -- MED_ADMIN: setup and tests. MED_PROVISIONER: validates patient ids inside its owner's-rights procedures.
  -- MED_CLINICAL_WRITER: owns the INTAKE write procedures, which re-check the actor's entitlement themselves.
  -- None of the three is granted to MED_API or to any U_<id> role.
  IS_ROLE_IN_SESSION('MED_ADMIN')
  OR IS_ROLE_IN_SESSION('MED_PROVISIONER')
  OR IS_ROLE_IN_SESSION('MED_CLINICAL_WRITER')
  OR EXISTS (
    SELECT 1 FROM {{DB}}.SECURITY.PATIENT_ENTITLEMENT e
    WHERE e.PATIENT_ID = patient_id
      AND e.REVOKED_AT IS NULL
      AND IS_ROLE_IN_SESSION(e.SNOWFLAKE_ROLE)
  );

CREATE ROW ACCESS POLICY IF NOT EXISTS PATIENT_OWN_RAP AS (patient_id VARCHAR, user_id VARCHAR) RETURNS BOOLEAN -> TRUE;
ALTER ROW ACCESS POLICY PATIENT_OWN_RAP SET BODY ->
  IS_ROLE_IN_SESSION('MED_ADMIN')
  OR (
    EXISTS (
      SELECT 1 FROM {{DB}}.SECURITY.APP_USER u
      WHERE u.USER_ID = user_id AND IS_ROLE_IN_SESSION(u.SNOWFLAKE_ROLE)
    )
    AND (
      patient_id IS NULL  -- an answer about no patient (a knowledge answer) belongs to its owner alone
      OR EXISTS (
        SELECT 1 FROM {{DB}}.SECURITY.PATIENT_ENTITLEMENT e
        WHERE e.PATIENT_ID = patient_id AND e.REVOKED_AT IS NULL AND IS_ROLE_IN_SESSION(e.SNOWFLAKE_ROLE)
      )
    )
  );

CREATE ROW ACCESS POLICY IF NOT EXISTS OWN_RAP AS (user_id VARCHAR) RETURNS BOOLEAN -> TRUE;
ALTER ROW ACCESS POLICY OWN_RAP SET BODY ->
  IS_ROLE_IN_SESSION('MED_ADMIN')
  OR EXISTS (
    SELECT 1 FROM {{DB}}.SECURITY.APP_USER u
    WHERE u.USER_ID = user_id AND IS_ROLE_IN_SESSION(u.SNOWFLAKE_ROLE)
  );

-- Attach (or re-attach) every policy. Safe to call repeatedly.
CREATE OR REPLACE PROCEDURE APPLY_POLICIES()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  patient_tables ARRAY DEFAULT ARRAY_CONSTRUCT(
    'CLINICAL.PATIENT','CLINICAL.ENCOUNTER','CLINICAL.DIAGNOSIS','CLINICAL.MEDICATION',
    'CLINICAL.LAB_RESULT','CLINICAL.ALLERGY','CLINICAL.PROCEDURE','CLINICAL.CLAIM','CLINICAL.CLINICAL_NOTE',
    'CLINICAL.RECORD_HISTORY','CLINICAL.REPORT','CLINICAL.REPORT_PAGE','CLINICAL.REPORT_ROW',
    'ANALYTICS.PATIENT_360','ANALYTICS.CURRENT_MEDICATIONS','ANALYTICS.PATIENT_LAB_LATEST',
    'ANALYTICS.PATIENT_TIMELINE','ANALYTICS.UTILIZATION','ANALYTICS.DASHBOARD_WORKLIST',
    'ANALYTICS.FINDING','ANALYTICS.LAB_REVIEW','ANALYTICS.PATIENT_EMBEDDING','ANALYTICS.PATIENT_SUMMARY');
  own_patient_tables ARRAY DEFAULT ARRAY_CONSTRUCT(
    'ANALYTICS.ANSWER','ANALYTICS.ANSWER_EVIDENCE','ANALYTICS.PIN','ANALYTICS.SAVED_VIEW');
  attached NUMBER DEFAULT 0;
  present NUMBER DEFAULT 0;
  t VARCHAR;
BEGIN
  FOR i IN 0 TO ARRAY_SIZE(patient_tables) - 1 DO
    t := patient_tables[i]::VARCHAR;
    -- A table a later script creates (08 and 09 call this procedure again at their end) is skipped for now.
    SELECT COUNT(*) INTO :present FROM {{DB}}.INFORMATION_SCHEMA.TABLES
      WHERE TABLE_SCHEMA = SPLIT_PART(:t, '.', 1) AND TABLE_NAME = SPLIT_PART(:t, '.', 2);
    IF (present = 0) THEN
      CONTINUE;
    END IF;
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE {{DB}}.' || t || ' DROP ROW ACCESS POLICY {{DB}}.SECURITY.PATIENT_RAP';
    EXCEPTION WHEN OTHER THEN NULL;
    END;
    EXECUTE IMMEDIATE 'ALTER TABLE {{DB}}.' || t || ' ADD ROW ACCESS POLICY {{DB}}.SECURITY.PATIENT_RAP ON (PATIENT_ID)';
    attached := attached + 1;
  END FOR;
  FOR j IN 0 TO ARRAY_SIZE(own_patient_tables) - 1 DO
    t := own_patient_tables[j]::VARCHAR;
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE {{DB}}.' || t || ' DROP ROW ACCESS POLICY {{DB}}.SECURITY.PATIENT_OWN_RAP';
    EXCEPTION WHEN OTHER THEN NULL;
    END;
    EXECUTE IMMEDIATE 'ALTER TABLE {{DB}}.' || t || ' ADD ROW ACCESS POLICY {{DB}}.SECURITY.PATIENT_OWN_RAP ON (PATIENT_ID, USER_ID)';
    attached := attached + 1;
  END FOR;
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE {{DB}}.ANALYTICS.COPILOT_AUDIT DROP ROW ACCESS POLICY {{DB}}.SECURITY.OWN_RAP';
  EXCEPTION WHEN OTHER THEN NULL;
  END;
  EXECUTE IMMEDIATE 'ALTER TABLE {{DB}}.ANALYTICS.COPILOT_AUDIT ADD ROW ACCESS POLICY {{DB}}.SECURITY.OWN_RAP ON (USER_ID)';
  attached := attached + 1;
  RETURN 'attached ' || attached || ' tables';
END;
$$;

CALL APPLY_POLICIES();
