-- 07_procedures.sql: PROVISION_USER, DEPROVISION_USER, SET_ENTITLEMENTS. Owned by MED_PROVISIONER.
-- Owner's-rights procedures: the API (MED_API) can call them but cannot create roles or grants itself.

USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
GRANT CREATE PROCEDURE ON SCHEMA {{DB}}.SECURITY TO ROLE MED_PROVISIONER;
GRANT SELECT, INSERT, UPDATE ON TABLE {{DB}}.SECURITY.APP_USER TO ROLE MED_PROVISIONER;
GRANT SELECT, INSERT, UPDATE ON TABLE {{DB}}.SECURITY.PATIENT_ENTITLEMENT TO ROLE MED_PROVISIONER;
GRANT INSERT ON TABLE {{DB}}.SECURITY.AUTH_EVENT TO ROLE MED_PROVISIONER;
GRANT SELECT ON TABLE {{DB}}.CLINICAL.PATIENT TO ROLE MED_PROVISIONER;

USE ROLE MED_PROVISIONER;
USE SCHEMA {{DB}}.SECURITY;

CREATE OR REPLACE PROCEDURE PROVISION_USER(
  P_USER_ID VARCHAR, P_EMAIL VARCHAR, P_DISPLAY_NAME VARCHAR, P_ROLE_CODE VARCHAR, P_IS_ADMIN BOOLEAN,
  P_SUPERVISING_DOCTOR_ID VARCHAR, P_PASSWORD_HASH VARCHAR, P_CREATED_BY VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  role_name VARCHAR;
  base_role VARCHAR;
  supervisor_ok NUMBER DEFAULT 0;
  existing NUMBER DEFAULT 0;
BEGIN
  IF (NOT REGEXP_LIKE(P_USER_ID, '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$')) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'invalid_user_id');
  END IF;
  IF (P_ROLE_CODE NOT IN ('DOCTOR', 'ASSISTANT')) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'invalid_role');
  END IF;
  IF (P_ROLE_CODE = 'ASSISTANT') THEN
    SELECT COUNT(*) INTO :supervisor_ok FROM {{DB}}.SECURITY.APP_USER
      WHERE USER_ID = :P_SUPERVISING_DOCTOR_ID AND ROLE_CODE = 'DOCTOR' AND STATUS = 'ACTIVE';
    IF (supervisor_ok = 0) THEN
      RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'supervisor_required');
    END IF;
  END IF;
  SELECT COUNT(*) INTO :existing FROM {{DB}}.SECURITY.APP_USER WHERE EMAIL = LOWER(:P_EMAIL) OR USER_ID = :P_USER_ID;
  IF (existing > 0) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'already_exists');
  END IF;

  role_name := 'U_' || REPLACE(UPPER(P_USER_ID), '-', '');
  base_role := IFF(P_ROLE_CODE = 'DOCTOR', 'MED_DOCTOR', 'MED_ASSISTANT');
  EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || role_name;
  EXECUTE IMMEDIATE 'GRANT ROLE ' || base_role || ' TO ROLE ' || role_name;
  -- To the service USER, never to the MED_API role (which would inherit every user's access).
  EXECUTE IMMEDIATE 'GRANT ROLE ' || role_name || ' TO USER MED_API_SVC';

  INSERT INTO {{DB}}.SECURITY.APP_USER (
    USER_ID, EMAIL, DISPLAY_NAME, ROLE_CODE, IS_ADMIN, SUPERVISING_DOCTOR_ID, STATUS, PASSWORD_HASH,
    PASSWORD_UPDATED_AT, FAILED_LOGINS, TOKEN_VERSION, SNOWFLAKE_ROLE, CREATED_AT, CREATED_BY)
  SELECT :P_USER_ID, LOWER(:P_EMAIL), :P_DISPLAY_NAME, :P_ROLE_CODE, :P_IS_ADMIN, :P_SUPERVISING_DOCTOR_ID,
         'ACTIVE', :P_PASSWORD_HASH, SYSDATE(), 0, 1, :role_name, SYSDATE(), :P_CREATED_BY;
  RETURN OBJECT_CONSTRUCT('ok', TRUE, 'snowflake_role', role_name);
END;
$$;

CREATE OR REPLACE PROCEDURE DEPROVISION_USER(P_USER_ID VARCHAR, P_ACTOR_ID VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  role_name VARCHAR;
BEGIN
  SELECT SNOWFLAKE_ROLE INTO :role_name FROM {{DB}}.SECURITY.APP_USER WHERE USER_ID = :P_USER_ID;
  IF (role_name IS NULL) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'user_not_found');
  END IF;
  UPDATE {{DB}}.SECURITY.PATIENT_ENTITLEMENT SET REVOKED_AT = SYSDATE()
    WHERE USER_ID = :P_USER_ID AND REVOKED_AT IS NULL;
  UPDATE {{DB}}.SECURITY.APP_USER SET STATUS = 'DISABLED', TOKEN_VERSION = TOKEN_VERSION + 1
    WHERE USER_ID = :P_USER_ID;
  EXECUTE IMMEDIATE 'REVOKE ROLE ' || role_name || ' FROM USER MED_API_SVC';
  INSERT INTO {{DB}}.SECURITY.AUTH_EVENT (EVENT_ID, EVENT_AT, EVENT_TYPE, USER_ID, ACTOR_ID)
    SELECT UUID_STRING(), SYSDATE(), 'USER_DISABLED', :P_USER_ID, :P_ACTOR_ID;
  RETURN OBJECT_CONSTRUCT('ok', TRUE);
END;
$$;

CREATE OR REPLACE PROCEDURE ENABLE_USER(P_USER_ID VARCHAR, P_ACTOR_ID VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  role_name VARCHAR;
BEGIN
  SELECT SNOWFLAKE_ROLE INTO :role_name FROM {{DB}}.SECURITY.APP_USER WHERE USER_ID = :P_USER_ID;
  IF (role_name IS NULL) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'user_not_found');
  END IF;
  EXECUTE IMMEDIATE 'GRANT ROLE ' || role_name || ' TO USER MED_API_SVC';
  UPDATE {{DB}}.SECURITY.APP_USER SET STATUS = 'ACTIVE', FAILED_LOGINS = 0, LOCKED_UNTIL = NULL,
         TOKEN_VERSION = TOKEN_VERSION + 1 WHERE USER_ID = :P_USER_ID;
  INSERT INTO {{DB}}.SECURITY.AUTH_EVENT (EVENT_ID, EVENT_AT, EVENT_TYPE, USER_ID, ACTOR_ID)
    SELECT UUID_STRING(), SYSDATE(), 'USER_ENABLED', :P_USER_ID, :P_ACTOR_ID;
  RETURN OBJECT_CONSTRUCT('ok', TRUE);
END;
$$;

CREATE OR REPLACE PROCEDURE SET_ENTITLEMENTS(P_USER_ID VARCHAR, P_PATIENT_IDS ARRAY, P_GRANTED_BY VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  target_role VARCHAR;
  target_code VARCHAR;
  supervisor VARCHAR;
  target_sf_role VARCHAR;
  unknown_ids ARRAY;
  not_supervisors NUMBER DEFAULT 0;
  added NUMBER DEFAULT 0;
BEGIN
  SELECT ROLE_CODE, SUPERVISING_DOCTOR_ID, SNOWFLAKE_ROLE INTO :target_code, :supervisor, :target_sf_role
    FROM {{DB}}.SECURITY.APP_USER WHERE USER_ID = :P_USER_ID AND STATUS = 'ACTIVE';
  IF (target_code IS NULL) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'user_not_found');
  END IF;

  SELECT ARRAY_AGG(f.VALUE::VARCHAR) INTO :unknown_ids
    FROM TABLE(FLATTEN(INPUT => :P_PATIENT_IDS)) f
    WHERE NOT EXISTS (SELECT 1 FROM {{DB}}.CLINICAL.PATIENT p WHERE p.PATIENT_ID = f.VALUE::VARCHAR);
  IF (unknown_ids IS NOT NULL AND ARRAY_SIZE(unknown_ids) > 0) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'unknown_patient', 'patient_ids', unknown_ids);
  END IF;

  IF (target_code = 'ASSISTANT') THEN
    SELECT COUNT(*) INTO :not_supervisors
      FROM TABLE(FLATTEN(INPUT => :P_PATIENT_IDS)) f
      WHERE NOT EXISTS (
        SELECT 1 FROM {{DB}}.SECURITY.PATIENT_ENTITLEMENT e
        WHERE e.USER_ID = :supervisor AND e.PATIENT_ID = f.VALUE::VARCHAR AND e.REVOKED_AT IS NULL);
    IF (not_supervisors > 0) THEN
      RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'not_supervisor_patient');
    END IF;
  END IF;

  UPDATE {{DB}}.SECURITY.PATIENT_ENTITLEMENT SET REVOKED_AT = SYSDATE()
    WHERE USER_ID = :P_USER_ID AND REVOKED_AT IS NULL
      AND PATIENT_ID NOT IN (SELECT f.VALUE::VARCHAR FROM TABLE(FLATTEN(INPUT => :P_PATIENT_IDS)) f);

  INSERT INTO {{DB}}.SECURITY.PATIENT_ENTITLEMENT
    (ENTITLEMENT_ID, PATIENT_ID, USER_ID, SNOWFLAKE_ROLE, GRANTED_BY, GRANTED_AT)
  SELECT UUID_STRING(), id, :P_USER_ID, :target_sf_role, :P_GRANTED_BY, SYSDATE()
    FROM (SELECT DISTINCT f.VALUE::VARCHAR AS id FROM TABLE(FLATTEN(INPUT => :P_PATIENT_IDS)) f) ids
    WHERE NOT EXISTS (
      SELECT 1 FROM {{DB}}.SECURITY.PATIENT_ENTITLEMENT e
      WHERE e.USER_ID = :P_USER_ID AND e.PATIENT_ID = ids.id AND e.REVOKED_AT IS NULL);
  added := SQLROWCOUNT;

  -- Taking a patient away from a doctor also takes it from that doctor's assistants.
  IF (target_code = 'DOCTOR') THEN
    UPDATE {{DB}}.SECURITY.PATIENT_ENTITLEMENT SET REVOKED_AT = SYSDATE()
      WHERE REVOKED_AT IS NULL
        AND USER_ID IN (SELECT USER_ID FROM {{DB}}.SECURITY.APP_USER WHERE SUPERVISING_DOCTOR_ID = :P_USER_ID)
        AND PATIENT_ID NOT IN (SELECT f.VALUE::VARCHAR FROM TABLE(FLATTEN(INPUT => :P_PATIENT_IDS)) f);
  END IF;

  INSERT INTO {{DB}}.SECURITY.AUTH_EVENT (EVENT_ID, EVENT_AT, EVENT_TYPE, USER_ID, ACTOR_ID, DETAIL)
    SELECT UUID_STRING(), SYSDATE(), 'ENTITLEMENT_CHANGE', :P_USER_ID, :P_GRANTED_BY,
           OBJECT_CONSTRUCT('patients', ARRAY_SIZE(:P_PATIENT_IDS), 'added', :added);
  RETURN OBJECT_CONSTRUCT('ok', TRUE, 'count', ARRAY_SIZE(P_PATIENT_IDS), 'added', added);
END;
$$;

GRANT USAGE ON PROCEDURE PROVISION_USER(VARCHAR, VARCHAR, VARCHAR, VARCHAR, BOOLEAN, VARCHAR, VARCHAR, VARCHAR) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE DEPROVISION_USER(VARCHAR, VARCHAR) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE SET_ENTITLEMENTS(VARCHAR, ARRAY, VARCHAR) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE ENABLE_USER(VARCHAR, VARCHAR) TO ROLE MED_API;
