-- 08_write_path.sql: the clinical write path (production plan, Phase 1). Run as MED_ADMIN. Idempotent.
--
-- Design (ADR-014, spike scripts/spikes/s_e_write_path.py): only owner's-rights procedures in INTAKE write CLINICAL.
-- They are owned by MED_CLINICAL_WRITER and called by the API's service role (MED_API) with the verified actor's user
-- id. Inside Snowflake each procedure re-checks that the actor is an active doctor entitled to the patient, so a
-- caller who skips the API check is still refused. Doctor and assistant roles (and every U_ role) stay read-only.
-- INVOKER_ROLE() cannot be used for this: inside an owner's-rights procedure it returns the owner (spike S-E).
USE ROLE MED_PROVISIONER;
CREATE ROLE IF NOT EXISTS MED_CLINICAL_WRITER
  COMMENT = 'Owns the INTAKE procedures, the only code that writes CLINICAL. Never granted to MED_API, MED_DOCTOR or a U_ role.';
GRANT ROLE MED_CLINICAL_WRITER TO USER {{ADMIN_USER}};

USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE DATABASE {{DB}};

CREATE SCHEMA IF NOT EXISTS INTAKE COMMENT = 'Intake procedures: the write path into CLINICAL, and request bookkeeping.';

GRANT USAGE ON DATABASE {{DB}} TO ROLE MED_CLINICAL_WRITER;
GRANT USAGE ON WAREHOUSE {{WH}} TO ROLE MED_CLINICAL_WRITER;
GRANT USAGE ON SCHEMA CLINICAL TO ROLE MED_CLINICAL_WRITER;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE MED_CLINICAL_WRITER;
GRANT USAGE ON SCHEMA SECURITY TO ROLE MED_CLINICAL_WRITER;
GRANT USAGE ON SCHEMA KNOWLEDGE TO ROLE MED_CLINICAL_WRITER;
GRANT USAGE ON SCHEMA INTAKE TO ROLE MED_CLINICAL_WRITER;
GRANT CREATE PROCEDURE ON SCHEMA INTAKE TO ROLE MED_CLINICAL_WRITER;
GRANT USAGE ON SCHEMA INTAKE TO ROLE MED_API;

-- Ids for new records. Seeded ids stay below these ranges (highest patient id P-2300, highest record number 258687).
CREATE SEQUENCE IF NOT EXISTS CLINICAL.PATIENT_SEQ START = 2301 INCREMENT = 1;
CREATE SEQUENCE IF NOT EXISTS CLINICAL.RECORD_SEQ START = 1000001 INCREMENT = 1;
GRANT USAGE ON SEQUENCE CLINICAL.PATIENT_SEQ TO ROLE MED_CLINICAL_WRITER;
GRANT USAGE ON SEQUENCE CLINICAL.RECORD_SEQ TO ROLE MED_CLINICAL_WRITER;

-- Archive, version and provenance columns on every table the write path touches ------------------------------
-- IS_ARCHIVED hides a row from every screen and read model; nothing is ever deleted at run time.
EXECUTE IMMEDIATE $$
DECLARE
  tables ARRAY DEFAULT ARRAY_CONSTRUCT('PATIENT', 'ENCOUNTER', 'DIAGNOSIS', 'MEDICATION', 'LAB_RESULT', 'ALLERGY', 'CLINICAL_NOTE');
  cols ARRAY DEFAULT ARRAY_CONSTRUCT(
    OBJECT_CONSTRUCT('n', 'IS_ARCHIVED', 'd', 'BOOLEAN NOT NULL DEFAULT FALSE'),
    OBJECT_CONSTRUCT('n', 'ARCHIVED_AT', 'd', 'TIMESTAMP_NTZ'),
    OBJECT_CONSTRUCT('n', 'ARCHIVED_BY', 'd', 'VARCHAR'),
    OBJECT_CONSTRUCT('n', 'VERSION', 'd', 'NUMBER NOT NULL DEFAULT 1'),
    OBJECT_CONSTRUCT('n', 'UPDATED_AT', 'd', 'TIMESTAMP_NTZ'),
    OBJECT_CONSTRUCT('n', 'UPDATED_BY', 'd', 'VARCHAR'),
    OBJECT_CONSTRUCT('n', 'ENTERED_BY', 'd', 'VARCHAR'),
    OBJECT_CONSTRUCT('n', 'ENTRY_SOURCE', 'd', 'VARCHAR'));
  t VARCHAR;
  cname VARCHAR;
  cdef VARCHAR;
  existing ARRAY;
  added NUMBER DEFAULT 0;
BEGIN
  FOR i IN 0 TO ARRAY_SIZE(tables) - 1 DO
    t := tables[i]::VARCHAR;
    SELECT ARRAY_AGG(COLUMN_NAME) INTO :existing FROM {{DB}}.INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = 'CLINICAL' AND TABLE_NAME = :t;
    FOR j IN 0 TO ARRAY_SIZE(cols) - 1 DO
      cname := cols[j]:n::VARCHAR;
      cdef := cols[j]:d::VARCHAR;
      IF (NOT ARRAY_CONTAINS(:cname::VARIANT, :existing)) THEN
        EXECUTE IMMEDIATE 'ALTER TABLE {{DB}}.CLINICAL.' || t || ' ADD COLUMN ' || cname || ' ' || cdef;
        added := added + 1;
      END IF;
    END FOR;
  END FOR;
  RETURN 'columns added: ' || added;
END;
$$;

-- Insert-only history of every write: who changed what, before and after ------------------------------------
CREATE TABLE IF NOT EXISTS CLINICAL.RECORD_HISTORY (
  HISTORY_ID VARCHAR NOT NULL,
  PATIENT_ID VARCHAR NOT NULL,
  ENTITY VARCHAR NOT NULL COMMENT 'PATIENT, DIAGNOSIS, MEDICATION, ALLERGY, LAB_RESULT, CLINICAL_NOTE or ENCOUNTER.',
  RECORD_ID VARCHAR NOT NULL,
  OP VARCHAR NOT NULL COMMENT 'CREATE, UPDATE, ARCHIVE or RESTORE.',
  BEFORE_JSON VARIANT,
  AFTER_JSON VARIANT,
  ACTOR_ID VARCHAR NOT NULL,
  REASON VARCHAR,
  ENTRY_SOURCE VARCHAR COMMENT 'MANUAL, or REPORT:<report id> once Phase 2 approvals write here.',
  AT TIMESTAMP_NTZ NOT NULL,
  PRIMARY KEY (HISTORY_ID)
) COMMENT = 'Append-only. One row per create, edit, archive or restore. Covered by the patient row access policy.';

-- Replays of a request that carried the same Idempotency-Key return the first result ---------------------------
CREATE TABLE IF NOT EXISTS INTAKE.REQUEST_LOG (
  REQUEST_KEY VARCHAR NOT NULL,
  ACTOR_ID VARCHAR NOT NULL,
  RESULT VARIANT,
  AT TIMESTAMP_NTZ NOT NULL,
  PRIMARY KEY (REQUEST_KEY, ACTOR_ID)
) COMMENT = 'Idempotency bookkeeping for the write path. No patient data. Service-side only.';

-- Read-model refreshes owed after a write. The API's background worker rebuilds each patient and marks the rows done;
-- a sweeper retries anything left over, so a restart never loses a refresh.
CREATE TABLE IF NOT EXISTS INTAKE.REFRESH_QUEUE (
  PATIENT_ID VARCHAR NOT NULL,
  ENQUEUED_AT TIMESTAMP_NTZ NOT NULL,
  DONE_AT TIMESTAMP_NTZ,
  ATTEMPTS NUMBER NOT NULL DEFAULT 0
) COMMENT = 'Outbox for read-model refreshes. Holds patient ids only. Service-side only.';

-- Privileges of the writer role --------------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON TABLE CLINICAL.PATIENT TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, UPDATE ON TABLE CLINICAL.ENCOUNTER TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, UPDATE ON TABLE CLINICAL.DIAGNOSIS TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, UPDATE ON TABLE CLINICAL.MEDICATION TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, UPDATE ON TABLE CLINICAL.LAB_RESULT TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, UPDATE ON TABLE CLINICAL.ALLERGY TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, UPDATE ON TABLE CLINICAL.CLINICAL_NOTE TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT ON TABLE CLINICAL.PROCEDURE TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT ON TABLE CLINICAL.CLAIM TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT ON TABLE CLINICAL.LAB_REFERENCE TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT ON TABLE CLINICAL.RECORD_HISTORY TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT ON TABLE SECURITY.APP_USER TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT ON TABLE SECURITY.PATIENT_ENTITLEMENT TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT ON TABLE KNOWLEDGE.DRUG TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT ON TABLE KNOWLEDGE.DRUG_NAME_MAP TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, DELETE ON TABLE ANALYTICS.PATIENT_360 TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, DELETE ON TABLE ANALYTICS.CURRENT_MEDICATIONS TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, DELETE ON TABLE ANALYTICS.PATIENT_LAB_LATEST TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, DELETE ON TABLE ANALYTICS.PATIENT_TIMELINE TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, DELETE ON TABLE ANALYTICS.UTILIZATION TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, DELETE ON TABLE ANALYTICS.DASHBOARD_WORKLIST TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE INTAKE.REQUEST_LOG TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE INTAKE.REFRESH_QUEUE TO ROLE MED_CLINICAL_WRITER;

-- RECORD_HISTORY is patient-keyed: attach the row access policy now that it exists.
CALL {{DB}}.SECURITY.APPLY_POLICIES();
