-- 25_link_medications.sql: set MEDICATION.DRUG_ID from KNOWLEDGE.DRUG_NAME_MAP. Run as MED_ADMIN, after the knowledge
-- load. A no-op while KNOWLEDGE is empty. Medications with no match keep DRUG_ID NULL: that is the "gap" case.
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE SCHEMA {{DB}}.CLINICAL;

UPDATE MEDICATION m SET DRUG_ID = NULL;

UPDATE MEDICATION m SET DRUG_ID = d.DRUG_ID
FROM (
  SELECT m2.MEDICATION_ID, MIN(n.DRUG_ID) AS DRUG_ID
  FROM MEDICATION m2
  JOIN {{DB}}.KNOWLEDGE.DRUG_NAME_MAP n
    ON LOWER(m2.DRUG_NAME) = n.NAME_TEXT OR LOWER(m2.DRUG_NAME) LIKE n.NAME_TEXT || ' %'
  JOIN {{DB}}.KNOWLEDGE.DRUG dr ON dr.DRUG_ID = n.DRUG_ID AND dr.IN_CORPUS
  GROUP BY m2.MEDICATION_ID
) d
WHERE m.MEDICATION_ID = d.MEDICATION_ID;
