-- 30_build_analytics.sql: precomputed read models (ADR-008). Run as MED_ADMIN. TRUNCATE + INSERT keeps comments and
-- the row access policy. "Recent" and change flags are relative to the as-of date {{AS_OF}}.
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE SCHEMA {{DB}}.ANALYTICS;

TRUNCATE TABLE DASHBOARD_WORKLIST;
TRUNCATE TABLE UTILIZATION;
TRUNCATE TABLE PATIENT_TIMELINE;
TRUNCATE TABLE PATIENT_LAB_LATEST;
TRUNCATE TABLE CURRENT_MEDICATIONS;
TRUNCATE TABLE PATIENT_360;

-- Baseline per patient: the visit before the latest one ---------------------------------------------------
CREATE OR REPLACE TEMPORARY TABLE VISITS AS
SELECT PATIENT_ID, ENCOUNTER_ID, STARTED_AT::DATE AS D, VISIT_KIND, DESCRIPTION,
       ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY STARTED_AT DESC, ENCOUNTER_ID DESC) AS RN
FROM {{DB}}.CLINICAL.ENCOUNTER
WHERE STARTED_AT::DATE <= '{{AS_OF}}'::DATE;

CREATE OR REPLACE TEMPORARY TABLE BASE AS
SELECT p.PATIENT_ID,
       l.ENCOUNTER_ID AS LAST_ENC_ID, l.D AS LAST_D, l.VISIT_KIND AS LAST_KIND, l.DESCRIPTION AS LAST_LABEL,
       pr.D AS PREV_D,
       COALESCE(pr.D, DATEADD('day', -90, '{{AS_OF}}'::DATE)) AS BASELINE
FROM {{DB}}.CLINICAL.PATIENT p
LEFT JOIN VISITS l ON l.PATIENT_ID = p.PATIENT_ID AND l.RN = 1
LEFT JOIN VISITS pr ON pr.PATIENT_ID = p.PATIENT_ID AND pr.RN = 2;

-- Current medications ----------------------------------------------------------------------------------
INSERT INTO CURRENT_MEDICATIONS
SELECT m.PATIENT_ID, m.MEDICATION_ID, m.DRUG_ID, m.DRUG_NAME, m.DESCRIPTION, m.DOSE_TEXT, m.START_DATE,
       m.LAST_CHANGE_DATE, m.CHANGE_NOTE, m.DRUG_ID IS NOT NULL
FROM {{DB}}.CLINICAL.MEDICATION m WHERE m.IS_ACTIVE;

-- Latest and previous result for the tests in LAB_REFERENCE -------------------------------------------------
INSERT INTO PATIENT_LAB_LATEST
WITH r AS (
  SELECT l.*, ref.SHORT_NAME,
         ROW_NUMBER() OVER (PARTITION BY l.PATIENT_ID, l.LOINC_CODE ORDER BY l.OBSERVED_AT DESC, l.LAB_ID DESC) AS RN
  FROM {{DB}}.CLINICAL.LAB_RESULT l
  JOIN {{DB}}.CLINICAL.LAB_REFERENCE ref ON ref.LOINC_CODE = l.LOINC_CODE
  WHERE l.VALUE_NUM IS NOT NULL AND l.OBSERVED_AT::DATE <= '{{AS_OF}}'::DATE
)
SELECT a.PATIENT_ID, a.LOINC_CODE, a.SHORT_NAME, a.TEST_NAME, a.LAB_ID, a.VALUE_NUM, a.OBSERVED_AT,
       b.LAB_ID, b.VALUE_NUM, b.OBSERVED_AT, a.UNIT, a.REF_LOW, a.REF_HIGH, a.ABNORMAL_FLAG,
       a.OBSERVED_AT::DATE > base.BASELINE
FROM r a
LEFT JOIN r b ON b.PATIENT_ID = a.PATIENT_ID AND b.LOINC_CODE = a.LOINC_CODE AND b.RN = 2
JOIN BASE base ON base.PATIENT_ID = a.PATIENT_ID
WHERE a.RN = 1;

-- Patient 360 -------------------------------------------------------------------------------------------
INSERT INTO PATIENT_360
WITH dx AS (
  SELECT PATIENT_ID,
         ARRAY_AGG(OBJECT_CONSTRUCT('diagnosis_id', DIAGNOSIS_ID, 'description', DESCRIPTION,
                                    'onset_year', YEAR(ONSET_DATE), 'code', CODE))
           WITHIN GROUP (ORDER BY ONSET_DATE DESC) AS ACTIVE_DX
  FROM {{DB}}.CLINICAL.DIAGNOSIS WHERE IS_ACTIVE GROUP BY PATIENT_ID
), medcount AS (
  SELECT PATIENT_ID, COUNT(*) AS N FROM CURRENT_MEDICATIONS GROUP BY PATIENT_ID
), newlab AS (
  SELECT l.PATIENT_ID, COUNT(*) AS N FROM PATIENT_LAB_LATEST l WHERE l.IS_NEW_SINCE_LAST_VISIT GROUP BY l.PATIENT_ID
), medchg AS (
  SELECT m.PATIENT_ID, MAX(GREATEST(COALESCE(m.LAST_CHANGE_DATE, m.START_DATE), COALESCE(m.START_DATE, m.LAST_CHANGE_DATE))) AS D
  FROM {{DB}}.CLINICAL.MEDICATION m
  WHERE COALESCE(m.LAST_CHANGE_DATE, m.START_DATE) <= '{{AS_OF}}'::DATE
  GROUP BY m.PATIENT_ID
), emerg AS (
  SELECT PATIENT_ID, MAX(D) AS D FROM VISITS WHERE VISIT_KIND = 'EMERGENCY' GROUP BY PATIENT_ID
), notes AS (
  SELECT PATIENT_ID, MAX(NOTE_DATE) AS D FROM {{DB}}.CLINICAL.CLINICAL_NOTE WHERE NOTE_DATE <= '{{AS_OF}}'::DATE GROUP BY PATIENT_ID
), lastlab AS (
  SELECT PATIENT_ID, MAX(LATEST_AT::DATE) AS D FROM PATIENT_LAB_LATEST GROUP BY PATIENT_ID
)
SELECT p.PATIENT_ID, p.FULL_NAME, FLOOR(DATEDIFF('day', p.BIRTH_DATE, '{{AS_OF}}'::DATE) / 365.25), p.SEX, p.CITY,
       COALESCE(dx.ACTIVE_DX, ARRAY_CONSTRUCT()),
       b.LAST_ENC_ID, b.LAST_D, b.LAST_KIND, b.LAST_LABEL, b.PREV_D,
       COALESCE(mc.N, 0), COALESCE(nl.N, 0), COALESCE(nl.N, 0) > 0,
       COALESCE(medchg.D > b.BASELINE, FALSE),
       COALESCE(emerg.D >= DATEADD('day', -7, '{{AS_OF}}'::DATE), FALSE),
       COALESCE(notes.D > b.LAST_D, FALSE),  -- a note newer than the last visit
       GREATEST_IGNORE_NULLS(b.LAST_D, lastlab.D, medchg.D, notes.D)
FROM {{DB}}.CLINICAL.PATIENT p
JOIN BASE b ON b.PATIENT_ID = p.PATIENT_ID
LEFT JOIN dx ON dx.PATIENT_ID = p.PATIENT_ID
LEFT JOIN medcount mc ON mc.PATIENT_ID = p.PATIENT_ID
LEFT JOIN newlab nl ON nl.PATIENT_ID = p.PATIENT_ID
LEFT JOIN medchg ON medchg.PATIENT_ID = p.PATIENT_ID
LEFT JOIN emerg ON emerg.PATIENT_ID = p.PATIENT_ID
LEFT JOIN notes ON notes.PATIENT_ID = p.PATIENT_ID
LEFT JOIN lastlab ON lastlab.PATIENT_ID = p.PATIENT_ID;

-- Timeline ------------------------------------------------------------------------------------------------
INSERT INTO PATIENT_TIMELINE
WITH ev AS (
  SELECT PATIENT_ID, STARTED_AT::DATE AS D, 'ENCOUNTER' AS T,
         CASE VISIT_KIND WHEN 'EMERGENCY' THEN 'Emergency visit' WHEN 'HOSPITALIZATION' THEN 'Hospital stay' ELSE 'Outpatient visit' END AS TITLE,
         COALESCE(REASON_DESCRIPTION, DESCRIPTION) AS SUMMARY, ENCOUNTER_ID AS REC, 'CLINICAL.ENCOUNTER' AS TBL, ENCOUNTER_ID AS ENC
  FROM {{DB}}.CLINICAL.ENCOUNTER
  UNION ALL
  SELECT PATIENT_ID, ONSET_DATE, 'DIAGNOSIS', 'Diagnosis', DESCRIPTION, DIAGNOSIS_ID, 'CLINICAL.DIAGNOSIS', ENCOUNTER_ID
  FROM {{DB}}.CLINICAL.DIAGNOSIS WHERE ONSET_DATE IS NOT NULL
  UNION ALL
  SELECT PATIENT_ID, START_DATE, 'MEDICATION_START', 'Medication started', COALESCE(DRUG_NAME, DESCRIPTION) || COALESCE(' ' || DOSE_TEXT, ''),
         MEDICATION_ID, 'CLINICAL.MEDICATION', ENCOUNTER_ID
  FROM {{DB}}.CLINICAL.MEDICATION WHERE START_DATE IS NOT NULL
  UNION ALL
  SELECT PATIENT_ID, LAST_CHANGE_DATE, 'MEDICATION_CHANGE', 'Medication change', COALESCE(CHANGE_NOTE, DRUG_NAME), MEDICATION_ID,
         'CLINICAL.MEDICATION', ENCOUNTER_ID
  FROM {{DB}}.CLINICAL.MEDICATION WHERE LAST_CHANGE_DATE IS NOT NULL
  UNION ALL
  SELECT l.PATIENT_ID, l.OBSERVED_AT::DATE, 'LAB_PANEL', 'Lab panel',
         LISTAGG(ref.SHORT_NAME || ' ' || TO_VARCHAR(l.VALUE_NUM, 'FM999990.0099'), ', ') WITHIN GROUP (ORDER BY ref.SHORT_NAME),
         MIN(l.LAB_ID), 'CLINICAL.LAB_RESULT', MIN(l.ENCOUNTER_ID)
  FROM {{DB}}.CLINICAL.LAB_RESULT l JOIN {{DB}}.CLINICAL.LAB_REFERENCE ref ON ref.LOINC_CODE = l.LOINC_CODE
  WHERE l.VALUE_NUM IS NOT NULL GROUP BY l.PATIENT_ID, l.OBSERVED_AT::DATE, l.ENCOUNTER_ID
  UNION ALL
  SELECT PATIENT_ID, SERVICE_DATE, 'CLAIM', 'Claim ' || LOWER(REPLACE(STATUS, '_', ' ')),
         CLAIM_ID || ', ' || TO_VARCHAR(BILLED_INR, '999,999,990') || ' INR' || COALESCE(', linked to ' || ENCOUNTER_ID, ''),
         CLAIM_ID, 'CLINICAL.CLAIM', ENCOUNTER_ID
  FROM {{DB}}.CLINICAL.CLAIM WHERE SERVICE_DATE IS NOT NULL
  UNION ALL
  SELECT PATIENT_ID, NOTE_DATE, 'NOTE', TITLE, LEFT(BODY, 120), NOTE_ID, 'CLINICAL.CLINICAL_NOTE', ENCOUNTER_ID
  FROM {{DB}}.CLINICAL.CLINICAL_NOTE
)
SELECT 'EV-' || ROW_NUMBER() OVER (ORDER BY PATIENT_ID, D, T, REC), PATIENT_ID, D, T, TITLE, SUMMARY, REC, TBL, ENC
FROM ev WHERE D IS NOT NULL AND D <= '{{AS_OF}}'::DATE;

-- Utilisation: trailing 12 months -------------------------------------------------------------------------
INSERT INTO UTILIZATION
WITH w AS (SELECT DATEADD('day', -365, '{{AS_OF}}'::DATE) AS FROM_D, '{{AS_OF}}'::DATE AS TO_D),
enc AS (
  SELECT e.PATIENT_ID,
         COUNT_IF(e.VISIT_KIND = 'OUTPATIENT') AS OPD, COUNT_IF(e.VISIT_KIND = 'EMERGENCY') AS ED,
         COUNT_IF(e.VISIT_KIND = 'HOSPITALIZATION') AS HOSP
  FROM {{DB}}.CLINICAL.ENCOUNTER e, w WHERE e.STARTED_AT::DATE BETWEEN w.FROM_D AND w.TO_D GROUP BY e.PATIENT_ID
), prc AS (
  SELECT x.PATIENT_ID, COUNT(*) AS N FROM {{DB}}.CLINICAL.PROCEDURE x, w
  WHERE x.PERFORMED_AT::DATE BETWEEN w.FROM_D AND w.TO_D GROUP BY x.PATIENT_ID
), clm AS (
  SELECT c.PATIENT_ID, SUM(c.BILLED_INR) AS BILLED, SUM(c.APPROVED_INR) AS APPROVED, SUM(c.OUTSTANDING_INR) AS OUTSTANDING
  FROM {{DB}}.CLINICAL.CLAIM c, w WHERE c.SERVICE_DATE BETWEEN w.FROM_D AND w.TO_D GROUP BY c.PATIENT_ID
)
SELECT p.PATIENT_ID, COALESCE(enc.OPD, 0), COALESCE(enc.ED, 0), COALESCE(enc.HOSP, 0), COALESCE(prc.N, 0),
       COALESCE(clm.BILLED, 0), COALESCE(clm.APPROVED, 0), COALESCE(clm.OUTSTANDING, 0)
FROM {{DB}}.CLINICAL.PATIENT p
LEFT JOIN enc ON enc.PATIENT_ID = p.PATIENT_ID LEFT JOIN prc ON prc.PATIENT_ID = p.PATIENT_ID
LEFT JOIN clm ON clm.PATIENT_ID = p.PATIENT_ID;

-- Worklist: one row per patient; the row access policy scopes it per user -----------------------------------------
INSERT INTO DASHBOARD_WORKLIST
SELECT PATIENT_ID, FULL_NAME, AGE_YEARS, SEX,
       ARRAY_SLICE(TRANSFORM(ACTIVE_DIAGNOSES, d -> d:description::VARCHAR), 0, 3),
       LAST_ENCOUNTER_DATE, LAST_ENCOUNTER_KIND, LAST_ENCOUNTER_LABEL,
       HAS_NEW_LAB, NEW_LAB_COUNT, HAS_NEW_MEDICATION_CHANGE, HAS_RECENT_EMERGENCY, HAS_NEW_DOCUMENT, LAST_CHANGE_DATE,
       IFF(HAS_NEW_LAB, 1, 0) + IFF(HAS_NEW_MEDICATION_CHANGE, 1, 0) + IFF(HAS_RECENT_EMERGENCY, 1, 0) + IFF(HAS_NEW_DOCUMENT, 1, 0)
FROM PATIENT_360;
