-- 35_refresh_patient.sql: rebuild one patient's read models after a write (production plan, P1.2). Created and
-- owned by MED_CLINICAL_WRITER.
--
-- The same logic as 30_build_analytics.sql, scoped to one patient. A patient who is archived or missing gets no
-- read-model rows, so every screen treats them as missing. P_AS_OF is the date "recent" is measured from: today in
-- production, or the pinned demo date. tests/integration/test_refresh_patient.py proves a refresh gives the same rows
-- as the bulk build.
USE ROLE MED_CLINICAL_WRITER;
USE WAREHOUSE {{WH}};
USE SCHEMA {{DB}}.INTAKE;

DROP PROCEDURE IF EXISTS REFRESH_PATIENT(VARCHAR, DATE);  -- replaced by the three-argument form below

CREATE OR REPLACE PROCEDURE REFRESH_PATIENT(P_PATIENT_ID VARCHAR, P_AS_OF DATE, P_FRESH BOOLEAN DEFAULT FALSE)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  alive NUMBER DEFAULT 0;
BEGIN
  -- A patient being registered has no read-model rows yet, so the six deletes (about half the statements, and each
  -- costs a round of compilation) are skipped: that keeps registering quick.
  IF (NOT P_FRESH) THEN
    DELETE FROM {{DB}}.ANALYTICS.DASHBOARD_WORKLIST WHERE PATIENT_ID = :P_PATIENT_ID;
    DELETE FROM {{DB}}.ANALYTICS.UTILIZATION WHERE PATIENT_ID = :P_PATIENT_ID;
    DELETE FROM {{DB}}.ANALYTICS.PATIENT_TIMELINE WHERE PATIENT_ID = :P_PATIENT_ID;
    DELETE FROM {{DB}}.ANALYTICS.PATIENT_LAB_LATEST WHERE PATIENT_ID = :P_PATIENT_ID;
    DELETE FROM {{DB}}.ANALYTICS.CURRENT_MEDICATIONS WHERE PATIENT_ID = :P_PATIENT_ID;
    DELETE FROM {{DB}}.ANALYTICS.PATIENT_360 WHERE PATIENT_ID = :P_PATIENT_ID;

    SELECT COUNT(*) INTO :alive FROM {{DB}}.CLINICAL.PATIENT WHERE PATIENT_ID = :P_PATIENT_ID AND NOT IS_ARCHIVED;
    IF (alive = 0) THEN
      RETURN 'removed';
    END IF;
  END IF;

  INSERT INTO {{DB}}.ANALYTICS.CURRENT_MEDICATIONS
  SELECT m.PATIENT_ID, m.MEDICATION_ID, m.DRUG_ID, m.DRUG_NAME, m.DESCRIPTION, m.DOSE_TEXT, m.START_DATE,
         m.LAST_CHANGE_DATE, m.CHANGE_NOTE, m.DRUG_ID IS NOT NULL
  FROM {{DB}}.CLINICAL.MEDICATION m
  WHERE m.PATIENT_ID = :P_PATIENT_ID AND m.IS_ACTIVE AND NOT m.IS_ARCHIVED;

  INSERT INTO {{DB}}.ANALYTICS.PATIENT_LAB_LATEST
  WITH visits AS (
    SELECT STARTED_AT::DATE AS D,
           ROW_NUMBER() OVER (ORDER BY STARTED_AT DESC, ENCOUNTER_ID DESC) AS RN
    FROM {{DB}}.CLINICAL.ENCOUNTER
    WHERE PATIENT_ID = :P_PATIENT_ID AND NOT IS_ARCHIVED AND STARTED_AT::DATE <= :P_AS_OF
  ), base AS (
    SELECT COALESCE((SELECT D FROM visits WHERE RN = 2), DATEADD('day', -90, :P_AS_OF)) AS BASELINE
  ), r AS (
    SELECT l.*, ref.SHORT_NAME,
           ROW_NUMBER() OVER (PARTITION BY l.LOINC_CODE ORDER BY l.OBSERVED_AT DESC, l.LAB_ID DESC) AS RN
    FROM {{DB}}.CLINICAL.LAB_RESULT l
    JOIN {{DB}}.CLINICAL.LAB_REFERENCE ref ON ref.LOINC_CODE = l.LOINC_CODE
    WHERE l.PATIENT_ID = :P_PATIENT_ID AND l.VALUE_NUM IS NOT NULL AND l.OBSERVED_AT::DATE <= :P_AS_OF
      AND NOT l.IS_ARCHIVED
  )
  SELECT a.PATIENT_ID, a.LOINC_CODE, a.SHORT_NAME, a.TEST_NAME, a.LAB_ID, a.VALUE_NUM, a.OBSERVED_AT,
         b.LAB_ID, b.VALUE_NUM, b.OBSERVED_AT, a.UNIT, a.REF_LOW, a.REF_HIGH, a.ABNORMAL_FLAG,
         a.OBSERVED_AT::DATE > base.BASELINE
  FROM r a
  LEFT JOIN r b ON b.LOINC_CODE = a.LOINC_CODE AND b.RN = 2
  CROSS JOIN base
  WHERE a.RN = 1;

  INSERT INTO {{DB}}.ANALYTICS.PATIENT_360
  WITH visits AS (
    SELECT ENCOUNTER_ID, STARTED_AT::DATE AS D, VISIT_KIND, DESCRIPTION,
           ROW_NUMBER() OVER (ORDER BY STARTED_AT DESC, ENCOUNTER_ID DESC) AS RN
    FROM {{DB}}.CLINICAL.ENCOUNTER
    WHERE PATIENT_ID = :P_PATIENT_ID AND NOT IS_ARCHIVED AND STARTED_AT::DATE <= :P_AS_OF
  ), l AS (SELECT * FROM visits WHERE RN = 1), pr AS (SELECT * FROM visits WHERE RN = 2),
  b AS (
    SELECT l.ENCOUNTER_ID AS LAST_ENC_ID, l.D AS LAST_D, l.VISIT_KIND AS LAST_KIND, l.DESCRIPTION AS LAST_LABEL,
           pr.D AS PREV_D, COALESCE(pr.D, DATEADD('day', -90, :P_AS_OF)) AS BASELINE
    FROM (SELECT 1 AS K) k LEFT JOIN l ON TRUE LEFT JOIN pr ON TRUE
  ), dx AS (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT('diagnosis_id', DIAGNOSIS_ID, 'description', DESCRIPTION,
                                      'onset_year', YEAR(ONSET_DATE), 'code', CODE))
             WITHIN GROUP (ORDER BY ONSET_DATE DESC) AS ACTIVE_DX
    FROM {{DB}}.CLINICAL.DIAGNOSIS WHERE PATIENT_ID = :P_PATIENT_ID AND IS_ACTIVE AND NOT IS_ARCHIVED
  ), medcount AS (
    SELECT COUNT(*) AS N FROM {{DB}}.ANALYTICS.CURRENT_MEDICATIONS WHERE PATIENT_ID = :P_PATIENT_ID
  ), newlab AS (
    SELECT COUNT(*) AS N FROM {{DB}}.ANALYTICS.PATIENT_LAB_LATEST
    WHERE PATIENT_ID = :P_PATIENT_ID AND IS_NEW_SINCE_LAST_VISIT
  ), medchg AS (
    SELECT MAX(GREATEST(COALESCE(LAST_CHANGE_DATE, START_DATE), COALESCE(START_DATE, LAST_CHANGE_DATE))) AS D
    FROM {{DB}}.CLINICAL.MEDICATION
    WHERE PATIENT_ID = :P_PATIENT_ID AND COALESCE(LAST_CHANGE_DATE, START_DATE) <= :P_AS_OF AND NOT IS_ARCHIVED
  ), emerg AS (
    SELECT MAX(D) AS D FROM visits WHERE VISIT_KIND = 'EMERGENCY'
  ), notes AS (
    SELECT MAX(NOTE_DATE) AS D FROM {{DB}}.CLINICAL.CLINICAL_NOTE
    WHERE PATIENT_ID = :P_PATIENT_ID AND NOTE_DATE <= :P_AS_OF AND NOT IS_ARCHIVED
  ), lastlab AS (
    SELECT MAX(LATEST_AT::DATE) AS D FROM {{DB}}.ANALYTICS.PATIENT_LAB_LATEST WHERE PATIENT_ID = :P_PATIENT_ID
  )
  SELECT p.PATIENT_ID, p.FULL_NAME, FLOOR(DATEDIFF('day', p.BIRTH_DATE, :P_AS_OF) / 365.25), p.SEX, p.CITY,
         COALESCE(dx.ACTIVE_DX, ARRAY_CONSTRUCT()),
         b.LAST_ENC_ID, b.LAST_D, b.LAST_KIND, b.LAST_LABEL, b.PREV_D,
         COALESCE(mc.N, 0), COALESCE(nl.N, 0), COALESCE(nl.N, 0) > 0,
         COALESCE(medchg.D > b.BASELINE, FALSE),
         COALESCE(emerg.D >= DATEADD('day', -7, :P_AS_OF), FALSE),
         COALESCE(notes.D > b.LAST_D, FALSE),
         GREATEST_IGNORE_NULLS(b.LAST_D, lastlab.D, medchg.D, notes.D)
  FROM {{DB}}.CLINICAL.PATIENT p
  CROSS JOIN b CROSS JOIN dx CROSS JOIN medcount mc CROSS JOIN newlab nl CROSS JOIN medchg
  CROSS JOIN emerg CROSS JOIN notes CROSS JOIN lastlab
  WHERE p.PATIENT_ID = :P_PATIENT_ID AND NOT p.IS_ARCHIVED;

  INSERT INTO {{DB}}.ANALYTICS.PATIENT_TIMELINE
  WITH ev AS (
    SELECT PATIENT_ID, STARTED_AT::DATE AS D, 'ENCOUNTER' AS T,
           CASE VISIT_KIND WHEN 'EMERGENCY' THEN 'Emergency visit' WHEN 'HOSPITALIZATION' THEN 'Hospital stay' ELSE 'Outpatient visit' END AS TITLE,
           COALESCE(REASON_DESCRIPTION, DESCRIPTION) AS SUMMARY, ENCOUNTER_ID AS REC, 'CLINICAL.ENCOUNTER' AS TBL, ENCOUNTER_ID AS ENC
    FROM {{DB}}.CLINICAL.ENCOUNTER WHERE PATIENT_ID = :P_PATIENT_ID AND NOT IS_ARCHIVED
    UNION ALL
    SELECT PATIENT_ID, ONSET_DATE, 'DIAGNOSIS', 'Diagnosis', DESCRIPTION, DIAGNOSIS_ID, 'CLINICAL.DIAGNOSIS', ENCOUNTER_ID
    FROM {{DB}}.CLINICAL.DIAGNOSIS WHERE PATIENT_ID = :P_PATIENT_ID AND ONSET_DATE IS NOT NULL AND NOT IS_ARCHIVED
    UNION ALL
    SELECT PATIENT_ID, START_DATE, 'MEDICATION_START', 'Medication started', COALESCE(DRUG_NAME, DESCRIPTION) || COALESCE(' ' || DOSE_TEXT, ''),
           MEDICATION_ID, 'CLINICAL.MEDICATION', ENCOUNTER_ID
    FROM {{DB}}.CLINICAL.MEDICATION WHERE PATIENT_ID = :P_PATIENT_ID AND START_DATE IS NOT NULL AND NOT IS_ARCHIVED
    UNION ALL
    SELECT PATIENT_ID, LAST_CHANGE_DATE, 'MEDICATION_CHANGE', 'Medication change', COALESCE(CHANGE_NOTE, DRUG_NAME), MEDICATION_ID,
           'CLINICAL.MEDICATION', ENCOUNTER_ID
    FROM {{DB}}.CLINICAL.MEDICATION WHERE PATIENT_ID = :P_PATIENT_ID AND LAST_CHANGE_DATE IS NOT NULL AND NOT IS_ARCHIVED
    UNION ALL
    SELECT l.PATIENT_ID, l.OBSERVED_AT::DATE, 'LAB_PANEL', 'Lab panel',
           LISTAGG(ref.SHORT_NAME || ' ' || TO_VARCHAR(l.VALUE_NUM, 'FM999990.0099'), ', ') WITHIN GROUP (ORDER BY ref.SHORT_NAME),
           MIN(l.LAB_ID), 'CLINICAL.LAB_RESULT', MIN(l.ENCOUNTER_ID)
    FROM {{DB}}.CLINICAL.LAB_RESULT l JOIN {{DB}}.CLINICAL.LAB_REFERENCE ref ON ref.LOINC_CODE = l.LOINC_CODE
    WHERE l.PATIENT_ID = :P_PATIENT_ID AND l.VALUE_NUM IS NOT NULL AND NOT l.IS_ARCHIVED
    GROUP BY l.PATIENT_ID, l.OBSERVED_AT::DATE, l.ENCOUNTER_ID
    UNION ALL
    SELECT PATIENT_ID, SERVICE_DATE, 'CLAIM', 'Claim ' || LOWER(REPLACE(STATUS, '_', ' ')),
           CLAIM_ID || ', ' || TO_VARCHAR(BILLED_INR, '999,999,990') || ' INR' || COALESCE(', linked to ' || ENCOUNTER_ID, ''),
           CLAIM_ID, 'CLINICAL.CLAIM', ENCOUNTER_ID
    FROM {{DB}}.CLINICAL.CLAIM WHERE PATIENT_ID = :P_PATIENT_ID AND SERVICE_DATE IS NOT NULL
    UNION ALL
    SELECT PATIENT_ID, NOTE_DATE, 'NOTE', TITLE, LEFT(BODY, 120), NOTE_ID, 'CLINICAL.CLINICAL_NOTE', ENCOUNTER_ID
    FROM {{DB}}.CLINICAL.CLINICAL_NOTE WHERE PATIENT_ID = :P_PATIENT_ID AND NOT IS_ARCHIVED
  )
  SELECT 'EV-' || PATIENT_ID || '-' || LPAD(ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY D, T, REC)::VARCHAR, 6, '0'),
         PATIENT_ID, D, T, TITLE, SUMMARY, REC, TBL, ENC
  FROM ev WHERE D IS NOT NULL AND D <= :P_AS_OF;

  INSERT INTO {{DB}}.ANALYTICS.UTILIZATION
  WITH w AS (SELECT DATEADD('day', -365, :P_AS_OF) AS FROM_D, :P_AS_OF AS TO_D),
  enc AS (
    SELECT COUNT_IF(e.VISIT_KIND = 'OUTPATIENT') AS OPD, COUNT_IF(e.VISIT_KIND = 'EMERGENCY') AS ED,
           COUNT_IF(e.VISIT_KIND = 'HOSPITALIZATION') AS HOSP
    FROM {{DB}}.CLINICAL.ENCOUNTER e, w
    WHERE e.PATIENT_ID = :P_PATIENT_ID AND e.STARTED_AT::DATE BETWEEN w.FROM_D AND w.TO_D AND NOT e.IS_ARCHIVED
  ), prc AS (
    SELECT COUNT(*) AS N FROM {{DB}}.CLINICAL.PROCEDURE x, w
    WHERE x.PATIENT_ID = :P_PATIENT_ID AND x.PERFORMED_AT::DATE BETWEEN w.FROM_D AND w.TO_D
  ), clm AS (
    SELECT SUM(c.BILLED_INR) AS BILLED, SUM(c.APPROVED_INR) AS APPROVED, SUM(c.OUTSTANDING_INR) AS OUTSTANDING
    FROM {{DB}}.CLINICAL.CLAIM c, w WHERE c.PATIENT_ID = :P_PATIENT_ID AND c.SERVICE_DATE BETWEEN w.FROM_D AND w.TO_D
  )
  SELECT :P_PATIENT_ID, COALESCE(enc.OPD, 0), COALESCE(enc.ED, 0), COALESCE(enc.HOSP, 0), COALESCE(prc.N, 0),
         COALESCE(clm.BILLED, 0), COALESCE(clm.APPROVED, 0), COALESCE(clm.OUTSTANDING, 0)
  FROM enc CROSS JOIN prc CROSS JOIN clm;

  INSERT INTO {{DB}}.ANALYTICS.DASHBOARD_WORKLIST
  SELECT PATIENT_ID, FULL_NAME, AGE_YEARS, SEX,
         ARRAY_SLICE(TRANSFORM(ACTIVE_DIAGNOSES, d -> d:description::VARCHAR), 0, 3),
         LAST_ENCOUNTER_DATE, LAST_ENCOUNTER_KIND, LAST_ENCOUNTER_LABEL,
         HAS_NEW_LAB, NEW_LAB_COUNT, HAS_NEW_MEDICATION_CHANGE, HAS_RECENT_EMERGENCY, HAS_NEW_DOCUMENT, LAST_CHANGE_DATE,
         IFF(HAS_NEW_LAB, 1, 0) + IFF(HAS_NEW_MEDICATION_CHANGE, 1, 0) + IFF(HAS_RECENT_EMERGENCY, 1, 0) + IFF(HAS_NEW_DOCUMENT, 1, 0)
  FROM {{DB}}.ANALYTICS.PATIENT_360 WHERE PATIENT_ID = :P_PATIENT_ID;

  RETURN 'refreshed';
END;
$$;

-- Keep one patient's embedding current. A summary that has not changed is not embedded again, so most refreshes
-- cost nothing here. Called after REFRESH_PATIENT by the queue below; needs SNOWFLAKE.CORTEX_USER (00_bootstrap_writer).
CREATE OR REPLACE PROCEDURE REFRESH_EMBEDDING(P_PATIENT_ID VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  txt VARCHAR;
  h VARCHAR;
  same NUMBER DEFAULT 0;
BEGIN
  SELECT SUMMARY_TEXT, SHA2(SUMMARY_TEXT, 256) INTO :txt, :h
    FROM {{DB}}.ANALYTICS.PATIENT_CASE_SUMMARY WHERE PATIENT_ID = :P_PATIENT_ID;
  IF (txt IS NULL) THEN
    DELETE FROM {{DB}}.ANALYTICS.PATIENT_EMBEDDING WHERE PATIENT_ID = :P_PATIENT_ID;
    RETURN 'removed';
  END IF;
  SELECT COUNT(*) INTO :same FROM {{DB}}.ANALYTICS.PATIENT_EMBEDDING
    WHERE PATIENT_ID = :P_PATIENT_ID AND SUMMARY_HASH = :h;
  IF (same > 0) THEN
    RETURN 'unchanged';
  END IF;
  DELETE FROM {{DB}}.ANALYTICS.PATIENT_EMBEDDING WHERE PATIENT_ID = :P_PATIENT_ID;
  INSERT INTO {{DB}}.ANALYTICS.PATIENT_EMBEDDING
  SELECT :P_PATIENT_ID, :txt, :h, SNOWFLAKE.CORTEX.EMBED_TEXT_1024('snowflake-arctic-embed-l-v2.0', :txt),
         'snowflake-arctic-embed-l-v2.0', SYSDATE();
  RETURN 'embedded';
END;
$$;

-- The queue: the API's worker refreshes a patient and marks every refresh requested before it started as done -----
CREATE OR REPLACE PROCEDURE REFRESH_QUEUED(P_PATIENT_ID VARCHAR, P_AS_OF DATE)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  started TIMESTAMP_NTZ DEFAULT SYSDATE();
  outcome VARCHAR;
  embedded VARCHAR;
BEGIN
  UPDATE {{DB}}.INTAKE.REFRESH_QUEUE SET ATTEMPTS = ATTEMPTS + 1
    WHERE PATIENT_ID = :P_PATIENT_ID AND DONE_AT IS NULL;
  CALL {{DB}}.INTAKE.REFRESH_PATIENT(:P_PATIENT_ID, :P_AS_OF, FALSE) INTO :outcome;
  BEGIN  -- a failed embedding must never leave the read models stale or the queue stuck
    CALL {{DB}}.INTAKE.REFRESH_EMBEDDING(:P_PATIENT_ID) INTO :embedded;
  EXCEPTION WHEN OTHER THEN
    embedded := 'failed';
  END;
  UPDATE {{DB}}.INTAKE.REFRESH_QUEUE SET DONE_AT = SYSDATE()
    WHERE PATIENT_ID = :P_PATIENT_ID AND DONE_AT IS NULL AND ENQUEUED_AT <= :started;
  RETURN outcome;
END;
$$;

CREATE OR REPLACE PROCEDURE PENDING_REFRESH(P_PATIENT_ID VARCHAR)
RETURNS NUMBER
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  n NUMBER DEFAULT 0;
BEGIN
  SELECT COUNT(*) INTO :n FROM {{DB}}.INTAKE.REFRESH_QUEUE WHERE PATIENT_ID = :P_PATIENT_ID AND DONE_AT IS NULL;
  RETURN n;
END;
$$;

-- Patients whose refresh is overdue (older than P_AGE_SECONDS, fewer than 5 attempts): the sweeper retries these.
CREATE OR REPLACE PROCEDURE OVERDUE_REFRESHES(P_AGE_SECONDS NUMBER)
RETURNS ARRAY
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  ids ARRAY;
BEGIN
  SELECT ARRAY_AGG(DISTINCT PATIENT_ID) INTO :ids FROM {{DB}}.INTAKE.REFRESH_QUEUE
    WHERE DONE_AT IS NULL AND ATTEMPTS < 5 AND ENQUEUED_AT < DATEADD('second', -:P_AGE_SECONDS, SYSDATE());
  RETURN COALESCE(ids, ARRAY_CONSTRUCT());
END;
$$;

-- Setup and tests call REFRESH_PATIENT directly; the write procedures call it as their owner.
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.REFRESH_PATIENT(VARCHAR, DATE, BOOLEAN) TO ROLE MED_ADMIN;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.REFRESH_QUEUED(VARCHAR, DATE) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.PENDING_REFRESH(VARCHAR) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.OVERDUE_REFRESHES(NUMBER) TO ROLE MED_API;
