-- 37_report_procedures.sql: report upload, parsing, staged extraction and review (production plan Phase 2).
-- Created and owned by MED_CLINICAL_WRITER; called by the API's service role with the verified actor's user id (the
-- same trust model as 36_intake_procedures.sql). Run after 36.
--
-- The path of a report: CREATE_REPORT (upload) -> PARSE_REPORT (text of each page) -> the API extracts rows with a model,
-- checks every row against the page text, and hands the survivors to STAGE_ROWS -> a doctor accepts, edits or rejects each
-- row (DECIDE_ROW) -> BEGIN_APPROVAL returns what to write, the API writes each row through WRITE_RECORD with the source
-- REPORT:<id> and an idempotency key -> FINISH_REPORT records the outcome. Nothing reaches the record before approval.
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
-- Report files: encrypted, never reachable by doctor or assistant roles, served only by the API after an entitlement check.
CREATE STAGE IF NOT EXISTS {{DB}}.INTAKE.REPORT_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Uploaded patient reports (synthetic in this build). Read and written only by the API service role and the INTAKE procedures.';
GRANT READ, WRITE ON STAGE {{DB}}.INTAKE.REPORT_STAGE TO ROLE MED_API;
GRANT READ ON STAGE {{DB}}.INTAKE.REPORT_STAGE TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE {{DB}}.CLINICAL.REPORT TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE {{DB}}.CLINICAL.REPORT_PAGE TO ROLE MED_CLINICAL_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE {{DB}}.CLINICAL.REPORT_ROW TO ROLE MED_CLINICAL_WRITER;

USE ROLE MED_CLINICAL_WRITER;
USE SCHEMA {{DB}}.INTAKE;

-- Who may act: an active user who holds the patient; some steps need a doctor (an assistant uploads, a doctor decides).
CREATE OR REPLACE PROCEDURE CAN_ACT(P_ACTOR VARCHAR, P_PATIENT_ID VARCHAR, P_NEED_DOCTOR BOOLEAN)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  active NUMBER DEFAULT 0;
  entitled NUMBER DEFAULT 0;
BEGIN
  SELECT COUNT(DISTINCT IFF(u.STATUS = 'ACTIVE' AND (NOT :P_NEED_DOCTOR OR u.ROLE_CODE = 'DOCTOR'), u.USER_ID, NULL)),
         COUNT(e.ENTITLEMENT_ID)
    INTO :active, :entitled
    FROM {{DB}}.SECURITY.APP_USER u
    LEFT JOIN {{DB}}.SECURITY.PATIENT_ENTITLEMENT e
      ON e.USER_ID = u.USER_ID AND e.PATIENT_ID = :P_PATIENT_ID AND e.REVOKED_AT IS NULL
    WHERE u.USER_ID = :P_ACTOR;
  IF (active = 0) THEN
    RETURN 'forbidden';
  END IF;
  IF (entitled = 0) THEN
    RETURN 'denied';
  END IF;
  RETURN 'ok';
END;
$$;

CREATE OR REPLACE PROCEDURE CREATE_REPORT(
  P_ACTOR VARCHAR, P_PATIENT_ID VARCHAR, P_FILENAME VARCHAR, P_MIME VARCHAR, P_SIZE NUMBER, P_SHA VARCHAR, P_STAGE_PATH VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  verdict VARCHAR;
  existing VARCHAR;
  existing_status VARCHAR;
  rid VARCHAR;
BEGIN
  CALL {{DB}}.INTAKE.CAN_ACT(:P_ACTOR, :P_PATIENT_ID, FALSE) INTO :verdict;
  IF (verdict <> 'ok') THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', verdict);
  END IF;
  SELECT MAX(REPORT_ID), MAX(STATUS) INTO :existing, :existing_status FROM {{DB}}.CLINICAL.REPORT
    WHERE PATIENT_ID = :P_PATIENT_ID AND SHA256 = :P_SHA AND STATUS NOT IN ('REJECTED', 'FAILED');
  IF (existing IS NOT NULL) THEN
    RETURN OBJECT_CONSTRUCT('ok', TRUE, 'report_id', existing, 'duplicate', TRUE, 'status', existing_status);
  END IF;
  rid := 'RPT-' || UPPER(SUBSTR(UUID_STRING(), 1, 8));
  INSERT INTO {{DB}}.CLINICAL.REPORT
    (REPORT_ID, PATIENT_ID, FILENAME, MIME_TYPE, SIZE_BYTES, SHA256, STAGE_PATH, STATUS, UPLOADED_BY, UPLOADED_AT)
  SELECT :rid, :P_PATIENT_ID, :P_FILENAME, :P_MIME, :P_SIZE, :P_SHA, :P_STAGE_PATH, 'UPLOADED', :P_ACTOR, SYSDATE();
  RETURN OBJECT_CONSTRUCT('ok', TRUE, 'report_id', rid, 'duplicate', FALSE, 'status', 'UPLOADED');
END;
$$;

-- Read the pages of a stored file. A failure marks the report FAILED with a short reason, so nothing is left in limbo.
CREATE OR REPLACE PROCEDURE PARSE_REPORT(P_REPORT_ID VARCHAR, P_MAX_PAGES NUMBER)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  pid VARCHAR;
  path VARCHAR;
  mime VARCHAR;
  state VARCHAR;
  parsed VARIANT;
  pages VARIANT;
  n NUMBER DEFAULT 0;
BEGIN
  SELECT PATIENT_ID, STAGE_PATH, MIME_TYPE, STATUS INTO :pid, :path, :mime, :state
    FROM {{DB}}.CLINICAL.REPORT WHERE REPORT_ID = :P_REPORT_ID;
  IF (pid IS NULL OR state NOT IN ('UPLOADED', 'PARSING')) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'state');
  END IF;
  UPDATE {{DB}}.CLINICAL.REPORT SET STATUS = 'PARSING', ATTEMPTS = ATTEMPTS + 1 WHERE REPORT_ID = :P_REPORT_ID;
  BEGIN
    IF (mime = 'application/pdf') THEN
      SELECT SNOWFLAKE.CORTEX.PARSE_DOCUMENT('@{{DB}}.INTAKE.REPORT_STAGE', :path, {'mode': 'LAYOUT', 'page_split': TRUE}) INTO :parsed;
    ELSE
      SELECT SNOWFLAKE.CORTEX.PARSE_DOCUMENT('@{{DB}}.INTAKE.REPORT_STAGE', :path, {'mode': 'OCR'}) INTO :parsed;
    END IF;
    pages := parsed:pages;
    DELETE FROM {{DB}}.CLINICAL.REPORT_PAGE WHERE REPORT_ID = :P_REPORT_ID;
    IF (pages IS NOT NULL AND ARRAY_SIZE(pages) > 0) THEN
      n := ARRAY_SIZE(pages);
      IF (n > :P_MAX_PAGES) THEN
        UPDATE {{DB}}.CLINICAL.REPORT SET STATUS = 'FAILED', STATUS_DETAIL = 'More pages than the limit', PAGE_COUNT = :n
          WHERE REPORT_ID = :P_REPORT_ID;
        RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'too_many_pages', 'pages', n);
      END IF;
      INSERT INTO {{DB}}.CLINICAL.REPORT_PAGE (REPORT_ID, PATIENT_ID, PAGE_NO, PAGE_TEXT)
      SELECT :P_REPORT_ID, :pid, f.INDEX + 1, COALESCE(NULLIF(TRIM(f.VALUE:content::VARCHAR), ''), '(no text on this page)')
      FROM TABLE(FLATTEN(INPUT => :pages)) f;
    ELSE
      n := 1;
      INSERT INTO {{DB}}.CLINICAL.REPORT_PAGE (REPORT_ID, PATIENT_ID, PAGE_NO, PAGE_TEXT)
      SELECT :P_REPORT_ID, :pid, 1, COALESCE(NULLIF(TRIM(:parsed:content::VARCHAR), ''), '(no text on this page)');
    END IF;
    UPDATE {{DB}}.CLINICAL.REPORT SET PAGE_COUNT = :n WHERE REPORT_ID = :P_REPORT_ID;
    RETURN OBJECT_CONSTRUCT('ok', TRUE, 'pages', n);
  EXCEPTION WHEN OTHER THEN
    UPDATE {{DB}}.CLINICAL.REPORT SET STATUS = 'FAILED', STATUS_DETAIL = LEFT('Could not read the file: ' || SQLERRM, 300)
      WHERE REPORT_ID = :P_REPORT_ID;
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'parse_failed');
  END;
END;
$$;

CREATE OR REPLACE PROCEDURE REPORT_PAGES(P_REPORT_ID VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  pages VARIANT;
  pid VARCHAR;
  patient_name VARCHAR;
  patient_ref VARCHAR;
BEGIN
  SELECT PATIENT_ID INTO :pid FROM {{DB}}.CLINICAL.REPORT WHERE REPORT_ID = :P_REPORT_ID;
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT('page', PAGE_NO, 'text', PAGE_TEXT)) WITHIN GROUP (ORDER BY PAGE_NO) INTO :pages
    FROM {{DB}}.CLINICAL.REPORT_PAGE WHERE REPORT_ID = :P_REPORT_ID;
  SELECT FULL_NAME INTO :patient_name FROM {{DB}}.CLINICAL.PATIENT WHERE PATIENT_ID = :pid;
  RETURN OBJECT_CONSTRUCT('patient_id', pid, 'patient_name', patient_name, 'pages', COALESCE(pages, ARRAY_CONSTRUCT()));
END;
$$;

CREATE OR REPLACE PROCEDURE STAGE_ROWS(P_REPORT_ID VARCHAR, P_ROWS VARCHAR, P_META VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  pid VARCHAR;
  state VARCHAR;
  kept NUMBER DEFAULT 0;
BEGIN
  SELECT PATIENT_ID, STATUS INTO :pid, :state FROM {{DB}}.CLINICAL.REPORT WHERE REPORT_ID = :P_REPORT_ID;
  IF (pid IS NULL OR state <> 'PARSING') THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'state');
  END IF;
  DELETE FROM {{DB}}.CLINICAL.REPORT_ROW WHERE REPORT_ID = :P_REPORT_ID;
  INSERT INTO {{DB}}.CLINICAL.REPORT_ROW
    (ROW_ID, REPORT_ID, PATIENT_ID, KIND, FIELDS, COLLECTED_AT, TIME_KNOWN, SOURCE_PAGE, SOURCE_QUOTE, CONFIDENCE, FLAGS, STATUS)
  SELECT 'RRW-' || UPPER(SUBSTR(UUID_STRING(), 1, 8)), :P_REPORT_ID, :pid, f.VALUE:kind::VARCHAR, f.VALUE:fields,
         TRY_TO_TIMESTAMP_NTZ(f.VALUE:collected_at::VARCHAR), COALESCE(f.VALUE:time_known::BOOLEAN, FALSE),
         f.VALUE:source_page::NUMBER, f.VALUE:source_quote::VARCHAR, f.VALUE:confidence::NUMBER(4,3),
         COALESCE(f.VALUE:flags, ARRAY_CONSTRUCT()), 'PENDING'
  FROM TABLE(FLATTEN(INPUT => PARSE_JSON(:P_ROWS))) f;
  SELECT COUNT(*) INTO :kept FROM {{DB}}.CLINICAL.REPORT_ROW WHERE REPORT_ID = :P_REPORT_ID;
  UPDATE {{DB}}.CLINICAL.REPORT r
    SET STATUS = 'EXTRACTED', EXTRACTED_AT = SYSDATE(), ROWS_KEPT = :kept,
        NAME_ON_REPORT = m.d:name::VARCHAR, IDENTITY_STATUS = m.d:identity::VARCHAR, MODEL = m.d:model::VARCHAR,
        ROWS_DROPPED = m.d:dropped::NUMBER, STATUS_DETAIL = m.d:note::VARCHAR
    FROM (SELECT PARSE_JSON(:P_META) AS d) m
    WHERE r.REPORT_ID = :P_REPORT_ID;
  RETURN OBJECT_CONSTRUCT('ok', TRUE, 'rows', kept);
END;
$$;

CREATE OR REPLACE PROCEDURE FAIL_REPORT(P_REPORT_ID VARCHAR, P_DETAIL VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
  UPDATE {{DB}}.CLINICAL.REPORT SET STATUS = 'FAILED', STATUS_DETAIL = LEFT(:P_DETAIL, 300)
    WHERE REPORT_ID = :P_REPORT_ID AND STATUS IN ('UPLOADED', 'PARSING');
  RETURN 'failed';
END;
$$;

CREATE OR REPLACE PROCEDURE DECIDE_ROW(
  P_ACTOR VARCHAR, P_PATIENT_ID VARCHAR, P_ROW_ID VARCHAR, P_DECISION VARCHAR, P_VERSION NUMBER,
  P_FIELDS VARCHAR, P_COLLECTED_AT VARCHAR, P_TIME_KNOWN BOOLEAN, P_FLAGS VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  verdict VARCHAR;
  current_version NUMBER;
  state VARCHAR;
  report_state VARCHAR;
  new_status VARCHAR;
BEGIN
  CALL {{DB}}.INTAKE.CAN_ACT(:P_ACTOR, :P_PATIENT_ID, TRUE) INTO :verdict;
  IF (verdict <> 'ok') THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', verdict);
  END IF;
  SELECT w.VERSION, w.STATUS, r.STATUS INTO :current_version, :state, :report_state
    FROM {{DB}}.CLINICAL.REPORT_ROW w JOIN {{DB}}.CLINICAL.REPORT r ON r.REPORT_ID = w.REPORT_ID
    WHERE w.ROW_ID = :P_ROW_ID AND w.PATIENT_ID = :P_PATIENT_ID;
  IF (current_version IS NULL) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'not_found');
  END IF;
  IF (current_version <> :P_VERSION) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'conflict', 'current_version', current_version);
  END IF;
  IF (state = 'APPROVED' OR report_state NOT IN ('EXTRACTED')) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'invalid', 'detail', 'This row can no longer be changed.');
  END IF;
  new_status := CASE P_DECISION WHEN 'ACCEPT' THEN 'ACCEPTED' WHEN 'REJECT' THEN 'REJECTED' WHEN 'EDIT' THEN 'EDITED' WHEN 'RESET' THEN 'PENDING' END;
  IF (new_status IS NULL) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'invalid', 'detail', 'unknown decision');
  END IF;
  IF (P_DECISION = 'EDIT') THEN
    UPDATE {{DB}}.CLINICAL.REPORT_ROW
      SET FIELDS = PARSE_JSON(:P_FIELDS), COLLECTED_AT = TRY_TO_TIMESTAMP_NTZ(:P_COLLECTED_AT), TIME_KNOWN = :P_TIME_KNOWN,
          FLAGS = PARSE_JSON(:P_FLAGS), STATUS = :new_status, DECIDED_BY = :P_ACTOR, DECIDED_AT = SYSDATE(), VERSION = VERSION + 1
      WHERE ROW_ID = :P_ROW_ID;
  ELSE
    UPDATE {{DB}}.CLINICAL.REPORT_ROW
      SET STATUS = :new_status, DECIDED_BY = IFF(:new_status = 'PENDING', NULL, :P_ACTOR),
          DECIDED_AT = IFF(:new_status = 'PENDING', NULL, SYSDATE()), VERSION = VERSION + 1
      WHERE ROW_ID = :P_ROW_ID;
  END IF;
  RETURN OBJECT_CONSTRUCT('ok', TRUE, 'row_id', P_ROW_ID, 'version', current_version + 1, 'status', new_status);
END;
$$;

-- Start an approval: checks the identity of the patient on the report, and returns the rows to write.
CREATE OR REPLACE PROCEDURE BEGIN_APPROVAL(P_ACTOR VARCHAR, P_PATIENT_ID VARCHAR, P_REPORT_ID VARCHAR, P_CONFIRM_IDENTITY BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  verdict VARCHAR;
  state VARCHAR;
  identity VARCHAR;
  confirmed VARCHAR;
  todo VARIANT;
BEGIN
  CALL {{DB}}.INTAKE.CAN_ACT(:P_ACTOR, :P_PATIENT_ID, TRUE) INTO :verdict;
  IF (verdict <> 'ok') THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', verdict);
  END IF;
  SELECT STATUS, IDENTITY_STATUS, IDENTITY_CONFIRMED_BY INTO :state, :identity, :confirmed
    FROM {{DB}}.CLINICAL.REPORT WHERE REPORT_ID = :P_REPORT_ID AND PATIENT_ID = :P_PATIENT_ID;
  IF (state IS NULL) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'not_found');
  END IF;
  IF (state <> 'EXTRACTED') THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'invalid', 'detail', 'This report is not waiting for review.');
  END IF;
  IF (identity = 'MISMATCH' AND confirmed IS NULL) THEN
    IF (NOT P_CONFIRM_IDENTITY) THEN
      RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'identity');
    END IF;
    UPDATE {{DB}}.CLINICAL.REPORT SET IDENTITY_CONFIRMED_BY = :P_ACTOR WHERE REPORT_ID = :P_REPORT_ID;
  END IF;
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT('row_id', ROW_ID, 'kind', KIND, 'fields', FIELDS, 'collected_at', COLLECTED_AT::VARCHAR,
                                    'time_known', TIME_KNOWN, 'version', VERSION)) INTO :todo
    FROM {{DB}}.CLINICAL.REPORT_ROW WHERE REPORT_ID = :P_REPORT_ID AND STATUS IN ('ACCEPTED', 'EDITED');
  RETURN OBJECT_CONSTRUCT('ok', TRUE, 'rows', COALESCE(todo, ARRAY_CONSTRUCT()));
END;
$$;

CREATE OR REPLACE PROCEDURE FINISH_REPORT(P_ACTOR VARCHAR, P_PATIENT_ID VARCHAR, P_REPORT_ID VARCHAR, P_RESULTS VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  verdict VARCHAR;
  open_rows NUMBER DEFAULT 0;
BEGIN
  CALL {{DB}}.INTAKE.CAN_ACT(:P_ACTOR, :P_PATIENT_ID, TRUE) INTO :verdict;
  IF (verdict <> 'ok') THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', verdict);
  END IF;
  UPDATE {{DB}}.CLINICAL.REPORT_ROW w
    SET STATUS = 'APPROVED', RECORD_ID = j.VALUE:record_id::VARCHAR, DECIDED_BY = :P_ACTOR, DECIDED_AT = SYSDATE(),
        VERSION = w.VERSION + 1
    FROM TABLE(FLATTEN(INPUT => PARSE_JSON(:P_RESULTS))) j
    WHERE w.ROW_ID = j.VALUE:row_id::VARCHAR AND w.REPORT_ID = :P_REPORT_ID AND w.PATIENT_ID = :P_PATIENT_ID;
  SELECT COUNT(*) INTO :open_rows FROM {{DB}}.CLINICAL.REPORT_ROW
    WHERE REPORT_ID = :P_REPORT_ID AND STATUS IN ('PENDING', 'ACCEPTED', 'EDITED');
  IF (open_rows = 0) THEN
    UPDATE {{DB}}.CLINICAL.REPORT SET STATUS = 'REVIEWED', REVIEWED_BY = :P_ACTOR, REVIEWED_AT = SYSDATE()
      WHERE REPORT_ID = :P_REPORT_ID;
  END IF;
  RETURN OBJECT_CONSTRUCT('ok', TRUE, 'open_rows', open_rows);
END;
$$;

CREATE OR REPLACE PROCEDURE REJECT_REPORT(P_ACTOR VARCHAR, P_PATIENT_ID VARCHAR, P_REPORT_ID VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  verdict VARCHAR;
  state VARCHAR;
BEGIN
  CALL {{DB}}.INTAKE.CAN_ACT(:P_ACTOR, :P_PATIENT_ID, TRUE) INTO :verdict;
  IF (verdict <> 'ok') THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', verdict);
  END IF;
  SELECT STATUS INTO :state FROM {{DB}}.CLINICAL.REPORT WHERE REPORT_ID = :P_REPORT_ID AND PATIENT_ID = :P_PATIENT_ID;
  IF (state IS NULL) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'not_found');
  END IF;
  IF (state NOT IN ('EXTRACTED', 'FAILED')) THEN
    RETURN OBJECT_CONSTRUCT('ok', FALSE, 'error', 'invalid', 'detail', 'This report cannot be rejected now.');
  END IF;
  UPDATE {{DB}}.CLINICAL.REPORT_ROW SET STATUS = 'REJECTED', DECIDED_BY = :P_ACTOR, DECIDED_AT = SYSDATE()
    WHERE REPORT_ID = :P_REPORT_ID AND STATUS <> 'APPROVED';
  UPDATE {{DB}}.CLINICAL.REPORT SET STATUS = 'REJECTED', REVIEWED_BY = :P_ACTOR, REVIEWED_AT = SYSDATE()
    WHERE REPORT_ID = :P_REPORT_ID;
  RETURN OBJECT_CONSTRUCT('ok', TRUE);
END;
$$;

-- Reports stuck before extraction (the API restarted mid-job): the sweeper retries these, at most three times.
CREATE OR REPLACE PROCEDURE STUCK_REPORTS(P_AGE_SECONDS NUMBER)
RETURNS ARRAY
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  ids ARRAY;
BEGIN
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT('report_id', REPORT_ID, 'uploaded_by', UPLOADED_BY)) INTO :ids FROM {{DB}}.CLINICAL.REPORT
    WHERE STATUS IN ('UPLOADED', 'PARSING') AND ATTEMPTS < 3
      AND UPLOADED_AT < DATEADD('second', -:P_AGE_SECONDS, SYSDATE());
  RETURN COALESCE(ids, ARRAY_CONSTRUCT());
END;
$$;

USE ROLE MED_CLINICAL_WRITER;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.CREATE_REPORT(VARCHAR, VARCHAR, VARCHAR, VARCHAR, NUMBER, VARCHAR, VARCHAR) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.PARSE_REPORT(VARCHAR, NUMBER) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.REPORT_PAGES(VARCHAR) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.STAGE_ROWS(VARCHAR, VARCHAR, VARCHAR) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.FAIL_REPORT(VARCHAR, VARCHAR) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.DECIDE_ROW(VARCHAR, VARCHAR, VARCHAR, VARCHAR, NUMBER, VARCHAR, VARCHAR, BOOLEAN, VARCHAR) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.BEGIN_APPROVAL(VARCHAR, VARCHAR, VARCHAR, BOOLEAN) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.FINISH_REPORT(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.REJECT_REPORT(VARCHAR, VARCHAR, VARCHAR) TO ROLE MED_API;
GRANT USAGE ON PROCEDURE {{DB}}.INTAKE.STUCK_REPORTS(NUMBER) TO ROLE MED_API;
