-- 50_search_service.sql: Cortex Search over the public document chunks (K-5). Build ONCE; rebuild only when the
-- corpus changes: DROP CORTEX SEARCH SERVICE KNOWLEDGE.LABEL_SEARCH via `db.py sql`, then apply this file (NFR-04).
-- IF NOT EXISTS keeps a full `db.py apply` from rebuilding the index and spending credits.
-- The index holds public documents only (SEC-04): no patient data, so no row access policy is needed.
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE SCHEMA {{DB}}.KNOWLEDGE;

CREATE CORTEX SEARCH SERVICE IF NOT EXISTS LABEL_SEARCH
  ON SEARCH_TEXT
  ATTRIBUTES DRUG_ID, DRUG_NAME, SECTION_KEY, SECTION_NAME, SOURCE, DOCUMENT_ID
  WAREHOUSE = {{WH}}
  TARGET_LAG = '{{SEARCH_LAG}}'
  COMMENT = 'Drug label and guideline chunks. Indexed once.'
AS (
  SELECT CHUNK_ID, SEARCH_TEXT, TEXT, DRUG_ID, DRUG_NAME, SECTION_KEY, SECTION_NAME, SOURCE, DOCUMENT_ID,
         TITLE, VERSION_LABEL, EFFECTIVE_DATE::VARCHAR AS EFFECTIVE_DATE, RETRIEVED_DATE::VARCHAR AS RETRIEVED_DATE, PAGE_NO
  FROM {{DB}}.KNOWLEDGE.DOCUMENT_CHUNK
);

GRANT USAGE ON CORTEX SEARCH SERVICE LABEL_SEARCH TO ROLE MED_API;
GRANT USAGE ON CORTEX SEARCH SERVICE LABEL_SEARCH TO ROLE MED_DOCTOR;
GRANT USAGE ON CORTEX SEARCH SERVICE LABEL_SEARCH TO ROLE MED_ASSISTANT;
GRANT USAGE ON CORTEX SEARCH SERVICE LABEL_SEARCH TO ROLE MED_AGENT_READ;
