-- 60_grants.sql: least-privilege grants per role. Run as MED_ADMIN after the tables exist. Idempotent.
-- Reviewed as a table in docs/database/README.md; 90_checks.sql fails on any unexpected grant.
--   MED_API        auth tables only; no privilege on any patient table
--   MED_DOCTOR /   read CLINICAL, ANALYTICS, KNOWLEDGE (row access policies filter it); insert answers, evidence,
--   MED_ASSISTANT  audit, pins, saved views; delete own pins. No write to CLINICAL.
--   MED_AGENT_READ read only
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE DATABASE {{DB}};

-- Base roles: read -------------------------------------------------------------------------------
GRANT SELECT ON ALL TABLES IN SCHEMA CLINICAL TO ROLE MED_DOCTOR;
GRANT SELECT ON ALL TABLES IN SCHEMA CLINICAL TO ROLE MED_ASSISTANT;
GRANT SELECT ON ALL TABLES IN SCHEMA CLINICAL TO ROLE MED_AGENT_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS TO ROLE MED_DOCTOR;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS TO ROLE MED_ASSISTANT;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS TO ROLE MED_AGENT_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA KNOWLEDGE TO ROLE MED_DOCTOR;
GRANT SELECT ON ALL TABLES IN SCHEMA KNOWLEDGE TO ROLE MED_ASSISTANT;
GRANT SELECT ON ALL TABLES IN SCHEMA KNOWLEDGE TO ROLE MED_AGENT_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CLINICAL TO ROLE MED_DOCTOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CLINICAL TO ROLE MED_ASSISTANT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS TO ROLE MED_DOCTOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS TO ROLE MED_ASSISTANT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA KNOWLEDGE TO ROLE MED_DOCTOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA KNOWLEDGE TO ROLE MED_ASSISTANT;

-- Base roles: run-time writes (answers, evidence, audit, pins, saved views) ------------------------------
GRANT INSERT ON TABLE ANALYTICS.ANSWER TO ROLE MED_DOCTOR;
GRANT INSERT ON TABLE ANALYTICS.ANSWER TO ROLE MED_ASSISTANT;
GRANT INSERT ON TABLE ANALYTICS.ANSWER_EVIDENCE TO ROLE MED_DOCTOR;
GRANT INSERT ON TABLE ANALYTICS.ANSWER_EVIDENCE TO ROLE MED_ASSISTANT;
GRANT INSERT ON TABLE ANALYTICS.COPILOT_AUDIT TO ROLE MED_DOCTOR;
GRANT INSERT ON TABLE ANALYTICS.COPILOT_AUDIT TO ROLE MED_ASSISTANT;
GRANT INSERT, DELETE ON TABLE ANALYTICS.PIN TO ROLE MED_DOCTOR;
GRANT INSERT, DELETE ON TABLE ANALYTICS.PIN TO ROLE MED_ASSISTANT;
GRANT INSERT ON TABLE ANALYTICS.SAVED_VIEW TO ROLE MED_DOCTOR;
GRANT INSERT ON TABLE ANALYTICS.SAVED_VIEW TO ROLE MED_ASSISTANT;
GRANT INSERT, UPDATE ON TABLE ANALYTICS.FINDING TO ROLE MED_DOCTOR;
GRANT INSERT, UPDATE ON TABLE ANALYTICS.FINDING TO ROLE MED_ASSISTANT;
GRANT INSERT, UPDATE ON TABLE ANALYTICS.GOLDEN_RUN TO ROLE MED_DOCTOR;
GRANT INSERT ON TABLE ANALYTICS.GOLDEN_RESULT TO ROLE MED_DOCTOR;

-- MED_API: accounts and sessions only -------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON TABLE SECURITY.APP_USER TO ROLE MED_API;
GRANT SELECT, INSERT, UPDATE ON TABLE SECURITY.USER_INVITE TO ROLE MED_API;
GRANT SELECT, INSERT, UPDATE ON TABLE SECURITY.AUTH_SESSION TO ROLE MED_API;
GRANT SELECT, INSERT ON TABLE SECURITY.AUTH_EVENT TO ROLE MED_API;
GRANT SELECT ON TABLE SECURITY.PATIENT_ENTITLEMENT TO ROLE MED_API;
GRANT SELECT ON TABLE KNOWLEDGE.SNAPSHOT TO ROLE MED_API;

-- Phase 4: drug requests are read and written by the API's service role.
GRANT SELECT, INSERT, UPDATE ON TABLE SECURITY.DRUG_REQUEST TO ROLE MED_API;
