-- 90_checks.sql: integrity, policy coverage, entitlement parity, scenario assertions (python scripts/db.py check).
-- Every result set is (CHECK_NAME, OK, DETAIL). Run as MED_ADMIN.
USE ROLE MED_ADMIN;
USE WAREHOUSE {{WH}};
USE DATABASE {{DB}};

SELECT 'row counts: alive patients in RAW equal generated patients in CLINICAL' AS CHECK_NAME,
       (SELECT COUNT(*) FROM RAW.PATIENTS WHERE DEATHDATE IS NULL) = (SELECT COUNT(*) FROM CLINICAL.PATIENT WHERE PATIENT_ID LIKE 'P-2%') AS OK,
       (SELECT COUNT(*) FROM CLINICAL.PATIENT)::VARCHAR || ' patients incl. seeded' AS DETAIL;

SELECT 'fk: encounter, diagnosis, medication, lab, procedure, claim and note patients exist' AS CHECK_NAME,
       NOT EXISTS (
         SELECT 1 FROM (
           SELECT PATIENT_ID FROM CLINICAL.ENCOUNTER UNION ALL SELECT PATIENT_ID FROM CLINICAL.DIAGNOSIS
           UNION ALL SELECT PATIENT_ID FROM CLINICAL.MEDICATION UNION ALL SELECT PATIENT_ID FROM CLINICAL.LAB_RESULT
           UNION ALL SELECT PATIENT_ID FROM CLINICAL.PROCEDURE UNION ALL SELECT PATIENT_ID FROM CLINICAL.CLAIM
           UNION ALL SELECT PATIENT_ID FROM CLINICAL.CLINICAL_NOTE) x
         WHERE x.PATIENT_ID IS NULL OR x.PATIENT_ID NOT IN (SELECT PATIENT_ID FROM CLINICAL.PATIENT)) AS OK,
       NULL AS DETAIL;

SELECT 'fk: every claim links to an existing encounter' AS CHECK_NAME,
       NOT EXISTS (SELECT 1 FROM CLINICAL.CLAIM c WHERE c.ENCOUNTER_ID IS NULL
                   OR c.ENCOUNTER_ID NOT IN (SELECT ENCOUNTER_ID FROM CLINICAL.ENCOUNTER)) AS OK, NULL AS DETAIL;

SELECT 'fk: child encounter ids exist' AS CHECK_NAME,
       NOT EXISTS (
         SELECT 1 FROM (SELECT ENCOUNTER_ID FROM CLINICAL.DIAGNOSIS UNION ALL SELECT ENCOUNTER_ID FROM CLINICAL.MEDICATION
                        UNION ALL SELECT ENCOUNTER_ID FROM CLINICAL.LAB_RESULT UNION ALL SELECT ENCOUNTER_ID FROM CLINICAL.PROCEDURE
                        UNION ALL SELECT ENCOUNTER_ID FROM CLINICAL.CLINICAL_NOTE) x
         WHERE x.ENCOUNTER_ID IS NOT NULL AND x.ENCOUNTER_ID NOT IN (SELECT ENCOUNTER_ID FROM CLINICAL.ENCOUNTER)) AS OK,
       NULL AS DETAIL;

SELECT 'fk: medication drug ids exist in KNOWLEDGE.DRUG when set' AS CHECK_NAME,
       NOT EXISTS (SELECT 1 FROM CLINICAL.MEDICATION WHERE DRUG_ID IS NOT NULL AND DRUG_ID NOT IN (SELECT DRUG_ID FROM KNOWLEDGE.DRUG)) AS OK,
       NULL AS DETAIL;

SELECT 'dates: no encounter ends before it starts' AS CHECK_NAME,
       NOT EXISTS (SELECT 1 FROM CLINICAL.ENCOUNTER WHERE ENDED_AT < STARTED_AT) AS OK, NULL AS DETAIL;

SELECT 'policy coverage: every PATIENT_ID table in CLINICAL and ANALYTICS has a row access policy' AS CHECK_NAME,
       COUNT(*) = 0 AS OK, LISTAGG(c.TABLE_SCHEMA || '.' || c.TABLE_NAME, ', ') AS DETAIL
FROM (SELECT DISTINCT c0.TABLE_SCHEMA, c0.TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS c0
      JOIN INFORMATION_SCHEMA.TABLES t0 ON t0.TABLE_SCHEMA = c0.TABLE_SCHEMA AND t0.TABLE_NAME = c0.TABLE_NAME
        AND t0.TABLE_TYPE = 'BASE TABLE'  -- a view cannot carry a policy; the tables it reads do (tested live)
      WHERE c0.COLUMN_NAME = 'PATIENT_ID' AND c0.TABLE_SCHEMA IN ('CLINICAL', 'ANALYTICS')) c
WHERE NOT EXISTS (
  SELECT 1 FROM (
    SELECT REF_SCHEMA_NAME, REF_ENTITY_NAME FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => '{{DB}}.SECURITY.PATIENT_RAP'))
    UNION ALL SELECT REF_SCHEMA_NAME, REF_ENTITY_NAME FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => '{{DB}}.SECURITY.PATIENT_OWN_RAP'))
    UNION ALL SELECT REF_SCHEMA_NAME, REF_ENTITY_NAME FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => '{{DB}}.SECURITY.OWN_RAP'))
  ) r WHERE r.REF_SCHEMA_NAME = c.TABLE_SCHEMA AND r.REF_ENTITY_NAME = c.TABLE_NAME);

SELECT 'entitlement parity: every assistant patient is also the supervising doctor''s' AS CHECK_NAME,
       NOT EXISTS (
         SELECT 1 FROM SECURITY.PATIENT_ENTITLEMENT e JOIN SECURITY.APP_USER a ON a.USER_ID = e.USER_ID AND a.ROLE_CODE = 'ASSISTANT'
         WHERE e.REVOKED_AT IS NULL AND NOT EXISTS (
           SELECT 1 FROM SECURITY.PATIENT_ENTITLEMENT d WHERE d.USER_ID = a.SUPERVISING_DOCTOR_ID
             AND d.PATIENT_ID = e.PATIENT_ID AND d.REVOKED_AT IS NULL)) AS OK, NULL AS DETAIL;

SELECT 'entitlement: S3 (P-1093) is not entitled to any assistant' AS CHECK_NAME,
       NOT EXISTS (SELECT 1 FROM SECURITY.PATIENT_ENTITLEMENT e JOIN SECURITY.APP_USER a ON a.USER_ID = e.USER_ID
                   WHERE e.PATIENT_ID = 'P-1093' AND a.ROLE_CODE = 'ASSISTANT' AND e.REVOKED_AT IS NULL) AS OK, NULL AS DETAIL;

SELECT 'entitlement: demo accounts exist (two doctors, one assistant)' AS CHECK_NAME,
       (SELECT COUNT_IF(ROLE_CODE = 'DOCTOR') FROM SECURITY.APP_USER) >= 2 AND (SELECT COUNT_IF(ROLE_CODE = 'ASSISTANT') FROM SECURITY.APP_USER) >= 1 AS OK,
       (SELECT COUNT(*) FROM SECURITY.APP_USER)::VARCHAR || ' users' AS DETAIL;

SELECT 'scenario S1: CKD, eGFR falling to below 45, metformin active with a change note' AS CHECK_NAME,
       EXISTS (SELECT 1 FROM CLINICAL.DIAGNOSIS WHERE PATIENT_ID = 'P-1042' AND DESCRIPTION ILIKE 'Chronic kidney disease%' AND IS_ACTIVE)
       AND EXISTS (SELECT 1 FROM ANALYTICS.PATIENT_LAB_LATEST WHERE PATIENT_ID = 'P-1042' AND SHORT_NAME = 'eGFR' AND LATEST_VALUE < 45 AND PREVIOUS_VALUE > LATEST_VALUE)
       AND EXISTS (SELECT 1 FROM CLINICAL.MEDICATION WHERE PATIENT_ID = 'P-1042' AND DRUG_NAME = 'Metformin' AND IS_ACTIVE AND CHANGE_NOTE IS NOT NULL) AS OK, NULL AS DETAIL;

SELECT 'scenario S2: control patient has two active medicines and normal labs' AS CHECK_NAME,
       (SELECT COUNT(*) FROM CLINICAL.MEDICATION WHERE PATIENT_ID = 'P-1067' AND IS_ACTIVE) = 2
       AND NOT EXISTS (SELECT 1 FROM ANALYTICS.PATIENT_LAB_LATEST WHERE PATIENT_ID = 'P-1067' AND ABNORMAL_FLAG IN ('LOW', 'HIGH')) AS OK, NULL AS DETAIL;

SELECT 'scenario S3: P-1093 exists with an entitlement for a doctor' AS CHECK_NAME,
       EXISTS (SELECT 1 FROM CLINICAL.PATIENT WHERE PATIENT_ID = 'P-1093')
       AND EXISTS (SELECT 1 FROM SECURITY.PATIENT_ENTITLEMENT e JOIN SECURITY.APP_USER a ON a.USER_ID = e.USER_ID
                   WHERE e.PATIENT_ID = 'P-1093' AND a.ROLE_CODE = 'DOCTOR' AND e.REVOKED_AT IS NULL) AS OK, NULL AS DETAIL;

SELECT 'scenario S4: a medication has no drug row in the corpus (gap)' AS CHECK_NAME,
       EXISTS (SELECT 1 FROM CLINICAL.MEDICATION WHERE PATIENT_ID = 'P-1101' AND IS_ACTIVE AND DRUG_ID IS NULL) AS OK, NULL AS DETAIL;

SELECT 'scenario S5: injection note exists and is marked' AS CHECK_NAME,
       EXISTS (SELECT 1 FROM CLINICAL.CLINICAL_NOTE WHERE PATIENT_ID = 'P-1118' AND CONTAINS_INJECTION) AS OK, NULL AS DETAIL;

SELECT 'ground truth: worklist has one row per patient' AS CHECK_NAME,
       (SELECT COUNT(*) FROM ANALYTICS.DASHBOARD_WORKLIST) = (SELECT COUNT(*) FROM CLINICAL.PATIENT) AS OK, NULL AS DETAIL;

SELECT 'ground truth: utilisation approved total equals the claim sum for P-1042' AS CHECK_NAME,
       (SELECT APPROVED_INR FROM ANALYTICS.UTILIZATION WHERE PATIENT_ID = 'P-1042')
         = (SELECT SUM(APPROVED_INR) FROM CLINICAL.CLAIM WHERE PATIENT_ID = 'P-1042'
              AND SERVICE_DATE BETWEEN DATEADD('day', -365, '{{AS_OF}}'::DATE) AND '{{AS_OF}}'::DATE) AS OK, NULL AS DETAIL;
