-- Ground truth: S1 (P-1042) utilisation over the trailing 365 days to the as-of date, restated from the raw
-- CLINICAL tables, not from the ANALYTICS read model. {{AS_OF}} is replaced by the test.
-- Compared with GET /patients/P-1042 utilization and GET /patients/P-1042/claims utilization.
WITH w AS (SELECT DATEADD('day', -365, '{{AS_OF}}'::DATE) AS FROM_D, '{{AS_OF}}'::DATE AS TO_D)
SELECT
  (SELECT COUNT_IF(e.VISIT_KIND = 'OUTPATIENT') FROM CLINICAL.ENCOUNTER e, w
    WHERE e.PATIENT_ID = 'P-1042' AND e.STARTED_AT::DATE BETWEEN w.FROM_D AND w.TO_D) AS OPD_VISITS,
  (SELECT COUNT_IF(e.VISIT_KIND = 'EMERGENCY') FROM CLINICAL.ENCOUNTER e, w
    WHERE e.PATIENT_ID = 'P-1042' AND e.STARTED_AT::DATE BETWEEN w.FROM_D AND w.TO_D) AS EMERGENCY_VISITS,
  (SELECT COUNT_IF(e.VISIT_KIND = 'HOSPITALIZATION') FROM CLINICAL.ENCOUNTER e, w
    WHERE e.PATIENT_ID = 'P-1042' AND e.STARTED_AT::DATE BETWEEN w.FROM_D AND w.TO_D) AS HOSPITALIZATIONS,
  (SELECT COUNT(*) FROM CLINICAL.PROCEDURE x, w
    WHERE x.PATIENT_ID = 'P-1042' AND x.PERFORMED_AT::DATE BETWEEN w.FROM_D AND w.TO_D) AS PROCEDURES,
  (SELECT COALESCE(SUM(c.BILLED_INR), 0) FROM CLINICAL.CLAIM c, w
    WHERE c.PATIENT_ID = 'P-1042' AND c.SERVICE_DATE BETWEEN w.FROM_D AND w.TO_D) AS BILLED_INR,
  (SELECT COALESCE(SUM(c.APPROVED_INR), 0) FROM CLINICAL.CLAIM c, w
    WHERE c.PATIENT_ID = 'P-1042' AND c.SERVICE_DATE BETWEEN w.FROM_D AND w.TO_D) AS APPROVED_INR;
