"""Write data/PROVENANCE.md: seed, settings and SHA-256 of every generated or downloaded input.

Run after the loaders (`poetry run python scripts/provenance.py`). Two runs on the same inputs give the same file,
so a changed hash means the data changed. Raw files are gitignored; this manifest is committed.
"""

import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYNTHEA = ROOT / "data" / "synthea"
OPENFDA = ROOT / "knowledge" / "raw" / "openfda"
SRC = (ROOT / "data" / "generate_synthea.py").read_text(encoding="utf-8")


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def table(files: list[Path], base: Path) -> list[str]:
    rows = ["| File | SHA-256 (first 16) | Bytes |", "| --- | --- | ---: |"]
    rows += [
        f"| {p.relative_to(base).as_posix()} | `{sha(p)}` | {p.stat().st_size} |" for p in files
    ]
    return rows if files else ["_Not present on this machine; run the loaders first._"]


def fetch_dates() -> str:
    dates: set[str] = set()
    for p in OPENFDA.glob("*.json"):
        meta = json.loads(p.read_text(encoding="utf-8")).get("meta", {}) if p.is_file() else {}
        dates.add(str(meta.get("last_updated") or meta.get("fetched_at") or "unknown"))
    return ", ".join(sorted(dates)) or "none fetched"


def main() -> None:
    seed = re.search(r"^SEED = (\d+)", SRC, re.M)
    pop = re.search(r"^POPULATION = (\d+)", SRC, re.M)
    jar = SYNTHEA / "synthea-with-dependencies.jar"
    out = [
        "# Data provenance",
        "",
        "Generated by `scripts/provenance.py`. All patient data is synthetic.",
        "",
        "## Synthea",
        f"- Seed: `{seed.group(1) if seed else '?'}`, population: {pop.group(1) if pop else '?'}, adults 35 to 90,"
        " reference date `DEMO_AS_OF_DATE`, CSV only (see `data/generate_synthea.py`)",
        f"- Jar SHA-256 (first 16): `{sha(jar)}`"
        if jar.exists()
        else "- Jar: not present on this machine",
        "",
        *table(sorted((SYNTHEA / "out" / "csv").glob("*.csv")), SYNTHEA),
        "",
        "## openFDA drug labels",
        f"- Source: https://api.fda.gov/drug/label.json, fetched unchanged by `knowledge/ingest/fetch_openfda.py`; response dates: {fetch_dates()}",
        "- openFDA terms: https://open.fda.gov/terms/ (labels are unvalidated; decision support only)",
        "",
        *table(sorted(OPENFDA.glob("*.json")), OPENFDA),
        "",
    ]
    (ROOT / "data" / "PROVENANCE.md").write_text("\n".join(out), encoding="utf-8")
    print("Wrote data/PROVENANCE.md")


if __name__ == "__main__":
    main()
